let activityRows=[],activityProfiles=new Map(),activitySetupMissing=false;
const ACTIVITY_SQL='https://supabase.com/dashboard/project/ypquqxolphrocdohcrrg/sql/new';
function activityData(row){return row.new_data||row.previous_data||{}}
function activityActor(id){return activityProfiles.get(id)||('Staff · '+String(id||'system').replace(/-/g,'').slice(0,7).toUpperCase())}
function activitySection(table,row){if(table==='operations_audit')return{key:row.record_type,label:{key_contacts:'Key contacts',complaint_records:'Complaints',accident_records:'Accidents'}[row.record_type]||'Operations'};return{product_audit:{key:'allergens',label:'Allergen matrix'},allergen_audit:{key:'allergens',label:'Allergen matrix'},booking_audit:{key:'bookings',label:'Table bookings'},document_audit:{key:'documents',label:'Forms & templates'},order_audit:{key:'orders',label:'Supplier orders'},coshh_audit:{key:'coshh',label:'COSHH'},training_audit:{key:'training',label:'Training log'},risk_audit:{key:'risk',label:'Risk assessments'},handbook_audit:{key:'handbook',label:'Staff handbook'}}[table]||{key:table,label:table}}
function activityName(table,row){const d=activityData(row);if(table==='product_audit'||table==='allergen_audit')return d.name||row.product_name||'Product';if(table==='booking_audit')return d.customer_name?`${d.customer_name}${d.booking_date?' · '+d.booking_date:''}${d.booking_time?' '+String(d.booking_time).slice(0,5):''}`:'Table booking';if(table==='order_audit')return `${d.supplier_name||'Supplier'} order`;if(table==='document_audit')return d.title||d.current_file_name||'Document';if(table==='coshh_audit')return d.product_name||'COSHH product';if(table==='training_audit')return[d.person_name,d.training_name].filter(Boolean).join(' · ')||'Training record';if(table==='handbook_audit')return d.title||'Handbook section';if(table==='risk_audit')return d.title||d.hazard||d.section_title||'Risk-assessment record';if(table==='operations_audit')return d.organisation||d.customer_name||d.person_name||'Operations record';return'Record'}
function activityRecordId(table,row){return String(row.product_id||row.booking_id||row.order_id||row.template_id||row.training_record_id||row.section_id||row.record_id||row.id)}
function activityAction(action){return({created:'Added',updated:'Updated',deleted:'Deleted',archived:'Archived',sent:'Sent',cancelled:'Cancelled',CREATED:'Added',UPDATED:'Updated',DELETED:'Deleted'}[action]||String(action||'Changed').replace(/_/g,' '))}
function activityDate(value){return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
async function loadActivity(){if(!isAdmin){activityRows=[];renderActivity();return}$('#activityState').textContent='Loading activity…';activitySetupMissing=false;const profiles=await db.from('profiles').select('id,display_name');activityProfiles=new Map((profiles.data||[]).map(x=>[x.id,x.display_name||'Staff member']));const sources=[['allergen_audit','id,product_id,product_name,action,changed_at,changed_by,old_data,new_data'],['booking_audit','id,booking_id,action,changed_at,changed_by,previous_data,new_data'],['order_audit','id,order_id,action,changed_at,changed_by,previous_data,new_data'],['document_audit','id,template_id,action,changed_at,changed_by,previous_data,new_data'],['coshh_audit','id,product_id,action,changed_at,changed_by,previous_data,new_data'],['training_audit','id,training_record_id,action,changed_at,changed_by,previous_data,new_data'],['risk_audit','id,table_name,record_id,action,changed_at,changed_by,previous_data,new_data'],['handbook_audit','id,section_id,action,changed_at,changed_by,previous_data,new_data'],['operations_audit','id,record_type,record_id,action,changed_at,changed_by,previous_data,new_data']];const results=await Promise.all(sources.map(async([table,fields])=>{const result=await db.from(table).select(fields).order('changed_at',{ascending:false}).limit(250);if(result.error){if(['booking_audit','handbook_audit'].includes(table))activitySetupMissing=true;return[]}return(result.data||[]).map(row=>({table,...row,previous_data:row.previous_data||row.old_data}))}));let acknowledgements=[];const ack=await db.from('risk_acknowledgements').select('id,assessment_id,user_id,version,acknowledged_at').order('acknowledged_at',{ascending:false}).limit(250);if(!ack.error)acknowledgements=(ack.data||[]).map(row=>({table:'risk_acknowledgements',id:row.id,record_id:row.assessment_id,action:'acknowledged',changed_at:row.acknowledged_at,changed_by:row.user_id,new_data:{version:row.version}}));activityRows=[...results.flat(),...acknowledgements].sort((a,b)=>new Date(b.changed_at)-new Date(a.changed_at)).slice(0,500);$('#activityState').textContent=activitySetupMissing?'Activity setup required':'Audit trail · up to date';renderActivity()}
function renderActivity(){const list=$('#activityList'),setup=$('#activitySetupMessage');if(!list)return;if(!isAdmin){list.innerHTML='<div class="handbook-empty"><strong>Administrator access is required.</strong></div>';return}setup.innerHTML=activitySetupMissing?`<div class="privacy-note"><strong>Finish Activity Log setup.</strong> Run <code>supabase-activity.sql</code> in the <a href="${ACTIVITY_SQL}" target="_blank" rel="noopener">Supabase SQL Editor</a> to add booking and handbook history plus automatic staff profiles.</div>`:'';const q=$('#activitySearch').value.trim().toLowerCase(),section=$('#activitySection').value,days=Number($('#activityPeriod').value||0),cutoff=days?Date.now()-days*86400000:0;const shown=activityRows.map(row=>{const meta=row.table==='risk_acknowledgements'?{key:'risk',label:'Risk assessments'}:activitySection(row.table,row);const name=row.table==='risk_acknowledgements'?`Assessment acknowledgement · version ${row.new_data?.version||''}`:activityName(row.table,row);const actor=activityActor(row.changed_by);return{row,meta,name,actor}}).filter(x=>(!section||x.meta.key===section)&&(!cutoff||new Date(x.row.changed_at).getTime()>=cutoff)&&(!q||[x.actor,x.meta.label,x.name,x.row.action].join(' ').toLowerCase().includes(q)));$('#activityCount').textContent=shown.length+' event'+(shown.length===1?'':'s');list.innerHTML=shown.length?shown.map(({row,meta,name,actor})=>`<article class="activity-card"><div class="activity-main"><span class="status-pill ${String(row.action).toLowerCase()==='deleted'||String(row.action).toLowerCase()==='archived'?'overdue':''}">${safe(activityAction(row.action))}</span><div><h3>${safe(name)}</h3><p>${safe(meta.label)} · ${safe(activityRecordId(row.table,row).slice(0,12))}</p></div></div><div class="activity-who"><strong>${safe(actor)}</strong><span>${safe(activityDate(row.changed_at))}</span></div></article>`).join(''):'<div class="handbook-empty">No activity matches these filters.</div>'}
window.loadActivity=loadActivity;

/* Allergen Register v2: shared Supabase persistence + visible product information */
window.addEventListener('DOMContentLoaded',()=>{
 const cols={Celery:'celery','Cereals containing gluten':'cereals_gluten',Crustaceans:'crustaceans',Eggs:'eggs',Fish:'fish',Lupin:'lupin',Milk:'milk',Molluscs:'molluscs',Mustard:'mustard',Nuts:'nuts',Peanuts:'peanuts',Sesame:'sesame',Soya:'soya',Sulphites:'sulphites'};
 const toItem=r=>({...r,allergens:Object.entries(cols).filter(([a,c])=>r[c]).map(([a])=>a)});
 const toRow=x=>{const r={name:x.name,category:x.category||'Other',notes:x.notes||'',active:x.active!==false,updated_by:currentUser?.id};Object.entries(cols).forEach(([a,c])=>r[c]=matchesAllergen(x,a));return r};
 async function seedAllergens(){if(!isAdmin)return false;const old=await db.from('products').select('name,category,allergens,notes,active').eq('active',true);if(old.error||!old.data?.length)return false;const seen=new Set(),rows=[];for(const x of old.data){const k=String(x.name).trim().toLowerCase();if(!k||seen.has(k))continue;seen.add(k);rows.push({...toRow(x),created_by:currentUser.id})}for(let i=0;i<rows.length;i+=75){const q=await db.from('allergen_products').insert(rows.slice(i,i+75));if(q.error)throw q.error}return true}
 window.loadProducts=async function(){if(!currentUser){items=[];setStatus('Sign in required');render();return}setStatus('Syncing…');let q=await db.from('allergen_products').select('*').eq('active',true).order('category').order('name');if(q.error){setStatus('Sync failed','error');showMessage(q.message);return}if(!q.data.length&&isAdmin){try{if(await seedAllergens())q=await db.from('allergen_products').select('*').eq('active',true).order('category').order('name')}catch(e){showMessage('Could not migrate existing allergen data: '+e.message)}}items=(q.data||[]).map(toItem);setStatus('Shared allergen data · saved ✓','ok');render();renderHome()};
 window.render=function(){refreshFilters();const q=$('#search').value.trim().toLowerCase(),c=$('#category').value,a=$('#allergen').value,diet=$('#dietary').value;const shown=items.filter(x=>{const flags=dietaryFlags(x),dietaryMatch=!diet||(diet==='vegan'&&flags.vegan)||(diet==='gf'&&flags.glutenFree)||(diet==='both'&&flags.vegan&&flags.glutenFree),allergens=standardAllergens(x.allergens);return dietaryMatch&&(!c||x.category===c)&&(!a||matchesAllergen(x,a))&&(!q||[x.name,x.category,x.notes,...allergens].join(' ').toLowerCase().includes(q))});$('#count').textContent=shown.length+' product'+(shown.length===1?'':'s');if(!currentUser){$('#grid').innerHTML='<div class="empty"><strong>Sign in to view the allergen matrix.</strong></div>';return}if(!shown.length){$('#grid').innerHTML='<div class="empty">No products match those filters.</div>';return}$('#grid').innerHTML=shown.map(x=>{const flags=dietaryFlags(x),info=cleanNotes(x.notes),may=(info.match(/may contain\s*:?[\s\S]*/i)||[])[0]||'';return `<article class="card"><div class="card-head"><div><h2>${safe(x.name)}</h2><div class="category">${safe(x.category||'Uncategorised')}</div></div><button class="edit-card" onclick="editItem('${x.id}')">Edit</button></div><div class="dietary"><span class="diet vegan ${flags.vegan?'yes':'no'}">${flags.vegan?'✓ Vegan':'Not vegan'}</span><span class="diet gf ${flags.glutenFree?'yes':'no'}">${flags.glutenFree?'✓ Gluten free':'Not gluten free'}</span></div><div class="badges">${standardAllergens(x.allergens).length?standardAllergens(x.allergens).map(y=>`<span class="badge">${safe(y)}</span>`).join(''):'<span class="badge none">No listed allergens</span>'}</div>${info?`<div style="margin-top:13px;padding:11px 12px;border-radius:11px;background:${may?'#fff4d8':'#f2f5f2'};border:1px solid ${may?'#ead28d':'#d8dfd8'}"><strong style="display:block;font-size:.78rem;text-transform:uppercase;letter-spacing:.04em;margin-bottom:3px">Product info</strong><span style="font-size:.9rem">${safe(info)}</span></div>`:''}<div class="actions"><button class="mini" onclick="editItem('${x.id}')">Edit</button><button class="mini danger" onclick="archiveItem('${x.id}')">Archive</button></div></article>`}).join('')};
 window.saveItem=async function(e){e.preventDefault();if(!isAdmin)return;const name=$('#name').value.trim();if(!name)return;const custom=$('#notes').value.trim(),notes=`Vegan: ${$('#vegan').checked?'Yes':'No'} · Gluten free: ${$('#glutenFree').checked?'Yes':'No'}${custom?' · '+custom:''}`,base={name,category:$('#itemCategory').value.trim()||'Other',notes,active:true,updated_by:currentUser.id},selected=standardAllergens([...document.querySelectorAll('#checks input:checked')].map(x=>x.value));Object.entries(cols).forEach(([a,c])=>base[c]=selected.includes(a)||(a==='Cereals containing gluten'&&GLUTEN_CEREALS.some(y=>selected.includes(y))));setStatus('Saving…');const result=editing?await db.from('allergen_products').update(base).eq('id',editing):await db.from('allergen_products').insert({...base,created_by:currentUser.id});if(result.error){setStatus('Save failed','error');return showMessage(result.error.message)}$('#editor').close();await loadProducts()};
 window.archiveItem=async id=>{const item=items.find(x=>x.id===id);if(!isAdmin||!item||!confirm('Archive '+item.name+'?'))return;setStatus('Saving…');const {error}=await db.from('allergen_products').update({active:false,updated_by:currentUser.id}).eq('id',id);if(error){setStatus('Save failed','error');return showMessage(error.message)}await loadProducts()};
 window.editItem=id=>openEditor(items.find(x=>x.id===id));
 $('#editForm').onsubmit=window.saveItem;$('#search').oninput=window.render;$('#dietary').onchange=window.render;$('#category').onchange=window.render;$('#allergen').onchange=window.render;
 const imp=$('#importBtn');if(imp)imp.style.display='none';
 loadProducts();
});
