// COGS editing, archive and delete enhancements
// Remove erroneous seeded item for new sessions; migrate existing browser data too.
if(!data.menuCleanupV1){data.products=data.products.filter(p=>p.name!=='Smashed Avo Mini');data.menuCleanupV1=true;localStorage.setItem('woods-cogs-v4',JSON.stringify(data));}

ingredientsView=function(){
 document.getElementById('panel').innerHTML=`<button class="primary" onclick="addIngredient()">+ Add Ingredient</button><p class="note">Edit the ingredient name, supplier pack cost, pack quantity or unit here. Changes flow through to every linked recipe.</p><div class="table"><table><thead><tr><th>Ingredient name</th><th>Pack cost £</th><th>Pack qty</th><th>Unit</th><th>Calculated unit cost</th><th></th></tr></thead><tbody>${data.ingredients.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(i=>`<tr><td><input type="text" value="${safe(i.name)}" onchange="editMaster('${i.id}','name',this.value)"></td><td><input type="number" step=".01" value="${i.packCost??''}" onchange="editMaster('${i.id}','packCost',this.value)"></td><td><input type="number" step=".01" value="${i.packQty??''}" onchange="editMaster('${i.id}','packQty',this.value)"></td><td><select onchange="editMaster('${i.id}','unit',this.value)">${['g','kg','ml','litre','each','slice','portion','bottle','can','pack'].map(u=>`<option ${i.unit===u?'selected':''}>${u}</option>`).join('')}</select></td><td>${unit(i)==null?'Needs cost':money(unit(i))+' / '+safe(i.unit)}</td><td><button onclick="deleteMaster('${i.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`;
};
function editMaster(id,key,value){const i=data.ingredients.find(x=>x.id===id);if(!i)return;if(key==='packCost'||key==='packQty')i[key]=value===''?null:Number(value);else i[key]=value.trim?value.trim():value;persist();ingredientsView()}
function deleteMaster(id){const i=data.ingredients.find(x=>x.id===id);if(!i)return;const used=data.products.filter(p=>(p.recipe||[]).some(r=>r.ingredientId===id));if(used.length){alert(`${i.name} is used in ${used.length} menu item${used.length===1?'':'s'}. Remove it from those recipes before deleting it.`);return}if(confirm(`Delete ${i.name} from the master cost list?`)){data.ingredients=data.ingredients.filter(x=>x.id!==id);persist();render()}}
function persist(){localStorage.setItem('woods-cogs-v4',JSON.stringify(data));}

// Override the menu category view to include item maintenance controls.
categoryView=function(){
 const ps=data.products.filter(p=>p.category===selectedCategory&&!p.archived);
 document.getElementById('panel').innerHTML=`<p><button onclick="view='categories';render()">← All categories</button> <button onclick="archivedView()">Archived Items (${data.products.filter(p=>p.archived).length})</button></p><h2>${safe(selectedCategory)}</h2><div class="cards">${ps.map(p=>{const c=cost(p),pct=p.price&&!c.incomplete?c.total/p.price*100:null,g=p.price&&!c.incomplete?p.price-c.total:null;return `<article><b>${safe(p.name)}</b><p>Selling price: ${money(p.price)}<br>Total cost: <strong>${c.incomplete?'Needs costs':money(c.total)}</strong><br>COGS: ${pct==null?'—':pct.toFixed(1)+'%'}<br>Gross contribution: ${g==null?'—':money(g)}</p><button onclick="editRecipe('${p.id}')">Recipe</button> <button onclick="editMenuItem('${p.id}')">Edit</button> <button onclick="archiveMenuItem('${p.id}')">Archive</button> <button onclick="deleteMenuItem('${p.id}')">Delete</button></article>`}).join('')||'<p>No active items in this category.</p>'}</div>`;
};

function editMenuItem(id){const p=data.products.find(x=>x.id===id);if(!p)return;const name=prompt('Menu item name',p.name);if(name===null||!name.trim())return;const price=prompt('Selling price (£)',p.price);if(price===null)return;const category=prompt('Category',p.category);if(category===null||!category.trim())return;p.name=name.trim();p.price=Number(price)||0;p.category=category.trim();if(!data.categories.includes(p.category))data.categories.push(p.category);persist();selectedCategory=p.category;view='category';render()}
function archiveMenuItem(id){const p=data.products.find(x=>x.id===id);if(!p)return;if(confirm(`Archive ${p.name}? It will leave the active menu but its recipe and costing will be retained.`)){p.archived=true;p.archivedAt=new Date().toISOString();persist();render()}}
function restoreMenuItem(id){const p=data.products.find(x=>x.id===id);if(!p)return;p.archived=false;delete p.archivedAt;persist();archivedView()}
function deleteMenuItem(id){const p=data.products.find(x=>x.id===id);if(!p)return;if(confirm(`Permanently delete ${p.name}? This cannot be undone.`)){data.products=data.products.filter(x=>x.id!==id);persist();render()}}
function archivedView(){
 const ps=data.products.filter(p=>p.archived).sort((a,b)=>a.name.localeCompare(b.name));
 document.getElementById('panel').innerHTML=`<p><button onclick="view='categories';render()">← Categories</button></p><h2>Archived Items</h2><p class="note">Archived items are kept for historical reference but do not appear in active menu categories.</p><div class="cards">${ps.map(p=>`<article><b>${safe(p.name)}</b><p>${safe(p.category)} · ${money(p.price)}</p><button onclick="editRecipe('${p.id}')">Recipe</button> <button onclick="restoreMenuItem('${p.id}')">Restore</button> <button onclick="deleteMenuItem('${p.id}')">Delete permanently</button></article>`).join('')||'<p>No archived items.</p>'}</div>`;
}

// Make category dashboard counts active items only and expose archive access globally.
categories=function(){document.getElementById('panel').innerHTML=`<p><button onclick="archivedView()">Archived Items (${data.products.filter(p=>p.archived).length})</button></p><div class="cards">${data.categories.map(c=>{const ps=data.products.filter(p=>p.category===c&&!p.archived),done=ps.filter(p=>!cost(p).incomplete).length;return `<article onclick="openCategory('${c.replace(/'/g,"\\'")}')" style="cursor:pointer"><b>${safe(c)}</b><p>${ps.length} active items · ${done} fully costed</p><button>Open category</button></article>`}).join('')}</div><p class="note">Open a category to see each active item's selling price, total recipe cost, COGS and gross contribution.</p>`};