let keyContacts=[],complaintRecords=[],accidentRecords=[],editingContact=null,editingComplaint=null,editingAccident=null;
const OPERATIONS_SQL='https://supabase.com/dashboard/project/ypquqxolphrocdohcrrg/sql/new';

function opDate(value){
 if(!value)return '';
 if(value instanceof Date&&!isNaN(value))return localISODate(value);
 if(typeof value==='number'){const d=new Date(Date.UTC(1899,11,30)+value*86400000);return d.toISOString().slice(0,10)}
 const s=String(value).trim(),m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{2,4})$/);
 if(m){const y=m[3].length===2?'20'+m[3]:m[3];return y+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0')}
 return /^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):'';
}
function opPrettyDate(value){return value?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value+'T12:00:00')):''}
function opTime(value){if(!value)return '';if(value instanceof Date&&!isNaN(value))return value.toISOString().slice(11,16);if(typeof value==='number'){const minutes=Math.round((value%1)*1440);return String(Math.floor(minutes/60)%24).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0')}const m=String(value).match(/\b(\d{1,2}):(\d{2})\b/);return m?m[1].padStart(2,'0')+':'+m[2]:String(value).trim()}
function opRef(prefix,id){return prefix+'-'+String(id||'').replace(/-/g,'').slice(0,7).toUpperCase()}
function opText(value){return safe(value).replace(/\r?\n|\s*\|\s*/g,'<br>')}
function opSetup(target,title){$(target).innerHTML=`<div class="handbook-empty"><strong>${safe(title)} setup is not complete yet.</strong><br>Run <code>supabase-operations.sql</code> in the <a href="${OPERATIONS_SQL}" target="_blank" rel="noopener">Supabase SQL Editor</a>.</div>`}

async function loadOperations(){await Promise.all([loadKeyContacts(),loadComplaints(),loadAccidents()])}
async function loadKeyContacts(){
 const setup=$('#contactsSetupMessage');if(!currentUser){keyContacts=[];setup.innerHTML='';renderKeyContacts();return}
 const {data,error}=await db.from('key_contacts').select('*').eq('active',true).order('organisation');
 if(error){keyContacts=[];opSetup('#contactsSetupMessage','Key Contacts');renderKeyContacts();return}
 setup.innerHTML='';keyContacts=data||[];renderKeyContacts();updateOperationsHomeCounts();
}
function renderKeyContacts(){
 const q=$('#contactSearch').value.trim().toLowerCase(),category=$('#contactCategory').value;
 const categories=[...new Set(keyContacts.map(x=>x.category).filter(Boolean))].sort();
 const current=$('#contactCategory').value;$('#contactCategory').innerHTML='<option value="">All categories</option>'+categories.map(x=>`<option>${safe(x)}</option>`).join('');$('#contactCategory').value=categories.includes(current)?current:'';
 const shown=keyContacts.filter(x=>(!category||x.category===category)&&(!q||[x.organisation,x.category,x.contact_name,x.phone,x.email,x.notes].join(' ').toLowerCase().includes(q)));
 $('#contactCount').textContent=shown.length+' contact'+(shown.length===1?'':'s');
 if(!currentUser){$('#contactsGrid').innerHTML='<div class="handbook-empty"><strong>Sign in to view key contacts.</strong></div>';return}
 $('#contactsGrid').innerHTML=shown.length?shown.map(x=>`<article class="contact-card"><div><span class="status-pill draft">${safe(x.category||'Contact')}</span><h3>${safe(x.organisation)}</h3>${x.contact_name?`<p>${safe(x.contact_name)}</p>`:''}</div><div class="contact-actions">${x.phone?`<a class="btn primary" href="tel:${safe(x.phone.replace(/[^+\d]/g,''))}">Call ${safe(x.phone)}</a>`:''}${x.email?`<a class="btn" href="mailto:${safe(x.email)}">Email</a>`:''}${x.website?`<a class="btn" href="${safe(/^https?:/i.test(x.website)?x.website:'https://'+x.website)}" target="_blank" rel="noopener">Website</a>`:''}</div>${x.notes?`<p class="contact-notes">${opText(x.notes)}</p>`:''}<div class="contact-admin-actions"><button class="mini" onclick="openContactEditor('${x.id}')">Edit</button><button class="mini danger" onclick="archiveContact('${x.id}')">Archive</button></div></article>`).join(''):'<div class="handbook-empty">No contacts match this search.</div>';
}
function openContactEditor(id=''){
 if(!isAdmin)return;const x=keyContacts.find(y=>y.id===id);editingContact=x?.id||null;$('#contactDialogTitle').textContent=x?'Edit contact':'Add contact';
 const map={contactOrganisation:'organisation',contactCategoryEdit:'category',contactNameEdit:'contact_name',contactPhone:'phone',contactEmail:'email',contactWebsite:'website',contactNotes:'notes'};Object.entries(map).forEach(([el,key])=>$('#'+el).value=x?.[key]||'');$('#contactEditor').showModal();
}
async function saveContact(e){e.preventDefault();if(!isAdmin)return;const value={organisation:$('#contactOrganisation').value.trim(),category:$('#contactCategoryEdit').value.trim()||'Supplier',contact_name:$('#contactNameEdit').value.trim(),phone:$('#contactPhone').value.trim(),email:$('#contactEmail').value.trim(),website:$('#contactWebsite').value.trim(),notes:$('#contactNotes').value.trim(),updated_by:currentUser.id};const result=editingContact?await db.from('key_contacts').update(value).eq('id',editingContact):await db.from('key_contacts').insert({...value,created_by:currentUser.id});if(result.error)return showMessage(result.error.message);$('#contactEditor').close();await loadKeyContacts()}
window.openContactEditor=openContactEditor;window.archiveContact=async id=>{if(!isAdmin||!confirm('Archive this contact?'))return;const {error}=await db.from('key_contacts').update({active:false,updated_by:currentUser.id}).eq('id',id);if(error)return showMessage(error.message);await loadKeyContacts()};

async function loadComplaints(){
 const setup=$('#complaintsSetupMessage');if(!currentUser){complaintRecords=[];setup.innerHTML='';renderComplaints();return}
 const {data,error}=await db.from('complaint_records').select('*').eq('active',true).order('date_received',{ascending:false});
 if(error){complaintRecords=[];opSetup('#complaintsSetupMessage','Complaints');renderComplaints();return}
 setup.innerHTML='';complaintRecords=data||[];renderComplaints();updateOperationsHomeCounts();
}
function complaintStatus(v){return v==='resolved'?'Resolved':v==='investigating'?'Investigating':'Open'}
function renderComplaints(){
 const q=$('#complaintSearch').value.trim().toLowerCase(),filter=$('#complaintFilter').value;const shown=complaintRecords.filter(x=>(!filter||x.status===filter)&&(!q||[x.customer_name,x.method,x.description,x.item_linked,x.supplier,x.action_taken,x.outcome].join(' ').toLowerCase().includes(q)));
 $('#complaintCount').textContent=shown.length+' record'+(shown.length===1?'':'s');$('#complaintOpenCount').textContent=complaintRecords.filter(x=>x.status!=='resolved').length+' open';
 if(!currentUser){$('#complaintsList').innerHTML='<div class="handbook-empty"><strong>Sign in to record or view complaints.</strong></div>';return}
 $('#complaintsList').innerHTML=shown.length?shown.map(x=>`<details class="secure-record"><summary><div><span class="secure-ref">${opRef('CMP',x.id)}</span><strong>${safe(x.customer_name)}</strong><small>${safe(opPrettyDate(x.date_received))}${x.method?' · '+safe(x.method):''}</small></div><span class="status-pill ${x.status==='resolved'?'':'due'}">${complaintStatus(x.status)}</span></summary><div class="secure-body"><div class="secure-fields">${opField('Contact',x.contact_details)}${opField('Visit',x.visit_date?opPrettyDate(x.visit_date)+(x.visit_time?' · '+x.visit_time:''):x.visit_time)}${opField('Party / table',[x.party_size,x.table_number].filter(Boolean).join(' · '))}${opField('Items ordered',x.items_ordered,true)}${opField('Item linked',x.item_linked)}${opField('Supplier',x.supplier)}${opField('Description',x.description,true)}${opField('Illness details',x.illness_details,true)}${opField('Food-safety review',x.food_safety_review,true)}${opField('Action taken',x.action_taken,true)}${opField('Outcome',x.outcome,true)}</div><div class="dialog-actions"><button class="btn" onclick="openComplaintEditor('${x.id}')">Edit record</button></div></div></details>`).join(''):'<div class="handbook-empty">No complaint records match this view.</div>';
}
function opField(label,value,wide=false){return value?`<div class="secure-field ${wide?'wide':''}"><small>${safe(label)}</small><p>${opText(value)}</p></div>`:''}
function openComplaintEditor(id=''){
 if(!currentUser)return;const x=complaintRecords.find(y=>y.id===id);editingComplaint=x?.id||null;$('#complaintDialogTitle').textContent=x?'Edit complaint':'Record complaint';
 const map={cmpDate:'date_received',cmpTime:'time_received',cmpReceivedBy:'received_by',cmpMethod:'method',cmpCustomer:'customer_name',cmpContact:'contact_details',cmpVisitDate:'visit_date',cmpVisitTime:'visit_time',cmpParty:'party_size',cmpTable:'table_number',cmpItems:'items_ordered',cmpItemLinked:'item_linked',cmpBatch:'batch_cooked',cmpSupplier:'supplier',cmpDescription:'description',cmpIllness:'illness_details',cmpOther:'other_complaints',cmpCount:'complaint_count',cmpReview:'food_safety_review',cmpAction:'action_taken',cmpOutcome:'outcome',cmpStatus:'status'};Object.entries(map).forEach(([el,key])=>$('#'+el).value=x?.[key]||'');if(!x)$('#cmpDate').value=localISODate();$('#complaintEditor').showModal();
}
async function saveComplaint(e){e.preventDefault();if(!currentUser)return;const value=complaintFormValue();value.updated_by=currentUser.id;const result=editingComplaint?await db.from('complaint_records').update(value).eq('id',editingComplaint):await db.from('complaint_records').insert({...value,created_by:currentUser.id});if(result.error)return showMessage(result.error.message);$('#complaintEditor').close();await loadComplaints();showMessage(editingComplaint?'Complaint updated.':'Complaint recorded securely.')}
function complaintFormValue(){return{date_received:$('#cmpDate').value,time_received:$('#cmpTime').value||null,received_by:$('#cmpReceivedBy').value.trim(),method:$('#cmpMethod').value.trim(),customer_name:$('#cmpCustomer').value.trim(),contact_details:$('#cmpContact').value.trim(),visit_date:$('#cmpVisitDate').value||null,visit_time:$('#cmpVisitTime').value.trim(),party_size:$('#cmpParty').value.trim(),table_number:$('#cmpTable').value.trim(),items_ordered:$('#cmpItems').value.trim(),item_linked:$('#cmpItemLinked').value.trim(),batch_cooked:$('#cmpBatch').value.trim(),supplier:$('#cmpSupplier').value.trim(),description:$('#cmpDescription').value.trim(),illness_details:$('#cmpIllness').value.trim(),other_complaints:$('#cmpOther').value.trim(),complaint_count:$('#cmpCount').value.trim(),food_safety_review:$('#cmpReview').value.trim(),action_taken:$('#cmpAction').value.trim(),outcome:$('#cmpOutcome').value.trim(),status:$('#cmpStatus').value}}
window.openComplaintEditor=openComplaintEditor;

async function loadAccidents(){
 const setup=$('#accidentsSetupMessage');if(!currentUser){accidentRecords=[];setup.innerHTML='';renderAccidents();return}
 const {data,error}=await db.from('accident_records').select('*').eq('active',true).order('incident_date',{ascending:false});
 if(error){accidentRecords=[];opSetup('#accidentsSetupMessage','Accident Records');renderAccidents();return}
 setup.innerHTML='';accidentRecords=data||[];renderAccidents();updateOperationsHomeCounts();
}
function accidentStatus(v){return v==='closed'?'Closed':v==='follow_up'?'Follow-up':'Open'}
function renderAccidents(){
 const q=$('#accidentSearch').value.trim().toLowerCase(),filter=$('#accidentFilter').value;const shown=accidentRecords.filter(x=>(!filter||x.status===filter)&&(!q||[x.person_name,x.location,x.incident_type,x.description,x.injury_nature,x.action_taken,x.follow_up].join(' ').toLowerCase().includes(q)));
 $('#accidentCount').textContent=shown.length+' record'+(shown.length===1?'':'s');$('#accidentOpenCount').textContent=accidentRecords.filter(x=>x.status!=='closed').length+' open';
 if(!currentUser){$('#accidentsList').innerHTML='<div class="handbook-empty"><strong>Sign in to record or view accidents.</strong></div>';return}
 $('#accidentsList').innerHTML=shown.length?shown.map(x=>`<details class="secure-record"><summary><div><span class="secure-ref">${opRef('ACC',x.id)}</span><strong>${safe(x.person_name)}</strong><small>${safe(opPrettyDate(x.incident_date))}${x.incident_type?' · '+safe(x.incident_type):''}</small></div><span class="status-pill ${x.status==='closed'?'':'due'}">${accidentStatus(x.status)}</span></summary><div class="secure-body"><div class="secure-fields">${opField('Time / location',[x.incident_time,x.location].filter(Boolean).join(' · '))}${opField('Contact',x.contact_details)}${opField('Person', [x.person_status,x.age].filter(Boolean).join(' · '))}${opField('Description',x.description,true)}${opField('Injury',x.injury_nature,true)}${opField('Body part / visible injury',[x.body_part,x.visible_injury].filter(Boolean).join(' · '),true)}${opField('Person’s account',x.person_account,true)}${opField('Immediate action',x.action_taken,true)}${opField('Witnesses',[x.witness_names,x.witness_contacts,x.witness_status].filter(Boolean).join(' · '),true)}${opField('Conditions',x.environmental_conditions,true)}${opField('Follow-up',x.follow_up,true)}${opField('Completed by',[x.completed_by,x.completed_by_role].filter(Boolean).join(' · '))}</div><div class="dialog-actions"><button class="btn" onclick="openAccidentEditor('${x.id}')">Edit record</button></div></div></details>`).join(''):'<div class="handbook-empty">No accident records match this view.</div>';
}
function openAccidentEditor(id=''){
 if(!currentUser)return;const x=accidentRecords.find(y=>y.id===id);editingAccident=x?.id||null;$('#accidentDialogTitle').textContent=x?'Edit accident record':'Record accident';
 const map={accDate:'incident_date',accTime:'incident_time',accLocation:'location',accType:'incident_type',accName:'person_name',accContact:'contact_details',accPersonStatus:'person_status',accAge:'age',accDescription:'description',accInjury:'injury_nature',accBodyPart:'body_part',accVisible:'visible_injury',accAccount:'person_account',accAction:'action_taken',accWitnessNames:'witness_names',accWitnessContacts:'witness_contacts',accWitnessStatus:'witness_status',accConditions:'environmental_conditions',accFollowUp:'follow_up',accCompletedBy:'completed_by',accRole:'completed_by_role',accStatus:'status'};Object.entries(map).forEach(([el,key])=>$('#'+el).value=x?.[key]||'');if(!x)$('#accDate').value=localISODate();$('#accidentEditor').showModal();
}
async function saveAccident(e){e.preventDefault();if(!currentUser)return;const value=accidentFormValue();value.updated_by=currentUser.id;const result=editingAccident?await db.from('accident_records').update(value).eq('id',editingAccident):await db.from('accident_records').insert({...value,created_by:currentUser.id});if(result.error)return showMessage(result.error.message);$('#accidentEditor').close();await loadAccidents();showMessage(editingAccident?'Accident record updated.':'Accident recorded securely.')}
function accidentFormValue(){return{incident_date:$('#accDate').value,incident_time:$('#accTime').value.trim(),location:$('#accLocation').value.trim(),incident_type:$('#accType').value.trim(),person_name:$('#accName').value.trim(),contact_details:$('#accContact').value.trim(),person_status:$('#accPersonStatus').value.trim(),age:$('#accAge').value.trim(),description:$('#accDescription').value.trim(),injury_nature:$('#accInjury').value.trim(),body_part:$('#accBodyPart').value.trim(),visible_injury:$('#accVisible').value.trim(),person_account:$('#accAccount').value.trim(),action_taken:$('#accAction').value.trim(),witness_names:$('#accWitnessNames').value.trim(),witness_contacts:$('#accWitnessContacts').value.trim(),witness_status:$('#accWitnessStatus').value.trim(),environmental_conditions:$('#accConditions').value.trim(),follow_up:$('#accFollowUp').value.trim(),completed_by:$('#accCompletedBy').value.trim(),completed_by_role:$('#accRole').value.trim(),status:$('#accStatus').value}}
window.openAccidentEditor=openAccidentEditor;

async function workbookRows(file){const buffer=await file.arrayBuffer(),book=XLSX.read(buffer,{type:'array',cellDates:true});return XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,defval:'',raw:true})}
function normHeader(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'')}
function rowObject(headers,row){const out={};headers.forEach((h,i)=>{if(h)out[normHeader(h)]=row[i]??''});return out}
function cleanPhone(v){return String(v??'').trim()}
function extractEmail(v){return (String(v||'').match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||''}
function extractWebsite(v){return (String(v||'').match(/(?:https?:\/\/|www\.)[^\s|]+/i)||[])[0]||''}
function scrubContactNotes(v){return String(v||'').split(/\s*\|\s*|\r?\n/).map(x=>x.trim()).filter(x=>x&&!/(password|username|membership\s*no|login\s*details|account\s*no)/i.test(x)).join(' · ')}
async function importContacts(){
 if(!isAdmin)return;const file=$('#contactsFile').files[0];if(!file)return showMessage('Choose the Woods contacts file first.');try{const rows=await workbookRows(file),hi=rows.findIndex(r=>r.some(v=>normHeader(v)==='supplier'));if(hi<0)throw new Error('Could not identify the contacts headings.');const headers=rows[hi];const data=rows.slice(hi+1).map(r=>rowObject(headers,r)).filter(r=>String(r.supplier||'').trim()).map(r=>{const notes=String(r.keynotes||''),alternatives=String(r.alternatives||'');return{organisation:String(r.supplier).trim(),category:String(r.type||'Supplier').trim()||'Supplier',contact_name:String(r.contactname||'').trim(),phone:cleanPhone(r.contactnumber),email:extractEmail(notes+' '+alternatives),website:extractWebsite(notes+' '+alternatives),notes:scrubContactNotes(notes+' | '+alternatives),created_by:currentUser.id,updated_by:currentUser.id}});if(!data.length)throw new Error('No contacts were found.');if(!confirm('Load '+data.length+' contacts? Login names and passwords will be excluded.'))return;if(keyContacts.length){const {error}=await db.from('key_contacts').update({active:false,updated_by:currentUser.id}).eq('active',true);if(error)throw error}const {error}=await db.from('key_contacts').insert(data);if(error)throw error;await loadKeyContacts();showMessage(data.length+' safe contact records loaded. Login credentials were not imported.')}catch(e){showMessage(e.message)}}
async function importComplaints(){
 if(!isAdmin)return;const file=$('#complaintsFile').files[0];if(!file)return showMessage('Choose the Woods complaints file first.');try{const rows=await workbookRows(file),hi=rows.findIndex(r=>r.some(v=>normHeader(v)==='incidentid'));if(hi<0)throw new Error('Could not identify the complaints headings.');const headers=rows[hi];const data=rows.slice(hi+1).map(r=>rowObject(headers,r)).filter(r=>r.datereceived&&r.customername).map(r=>({date_received:opDate(r.datereceived),time_received:opTime(r.timereceived)||null,received_by:String(r.receivedby||''),method:String(r.method||''),customer_name:String(r.customername||''),contact_details:String(r.contactdetails||''),visit_date:opDate(r.dateofvisit)||null,visit_time:opTime(r.approxtimeofvisit),party_size:String(r.numberinparty||''),table_number:String(r.tablenumber||''),items_ordered:String(r.itemsordered||''),item_linked:String(r.itemlinkedtocomplaint||''),batch_cooked:String(r.batchcookedyn||r.batchcookedyorn||''),supplier:String(r.supplier||''),description:String(r.description||''),illness_details:String(r.illnessdetails||''),other_complaints:String(r.othercomplaintsyn||r.othercomplaintsyorn||''),complaint_count:String(r.noofcomplaints||''),food_safety_review:String(r.foodsafetyreview||''),action_taken:String(r.actiontaken||''),outcome:String(r.outcome||''),status:'resolved',created_by:currentUser.id,updated_by:currentUser.id}));const added=await insertUnique('complaint_records',data,complaintRecords,x=>[x.date_received,x.customer_name,x.description].join('|'));await loadComplaints();showMessage(added+' complaint row'+(added===1?'':'s')+' loaded. Existing matches were skipped.')}catch(e){showMessage(e.message)}}
async function importAccidents(){
 if(!isAdmin)return;const file=$('#accidentsFile').files[0];if(!file)return showMessage('Choose the Woods accident file first.');try{const rows=await workbookRows(file),hi=rows.findIndex(r=>r.some(v=>normHeader(v)==='date')&&r.some(v=>normHeader(v)==='location'));if(hi<0)throw new Error('Could not identify the accident headings.');const data=rows.slice(hi+1).filter(r=>r[2]&&r[6]).map(r=>({incident_date:opDate(r[2]),incident_time:String(r[3]||''),location:String(r[4]||''),incident_type:String(r[5]||''),person_name:String(r[6]||''),contact_details:String(r[7]||''),person_status:String(r[8]||''),age:String(r[9]||''),description:String(r[10]||''),injury_nature:String(r[11]||''),body_part:String(r[12]||''),visible_injury:String(r[13]||''),person_account:String(r[14]||''),action_taken:String(r[15]||''),witness_names:String(r[16]||''),witness_contacts:String(r[17]||''),witness_status:String(r[18]||''),environmental_conditions:String(r[19]||''),follow_up:String(r[20]||''),completed_by:String(r[21]||''),completed_by_role:String(r[22]||''),status:'closed',created_by:currentUser.id,updated_by:currentUser.id}));const added=await insertUnique('accident_records',data,accidentRecords,x=>[x.incident_date,x.person_name,x.description].join('|'));await loadAccidents();showMessage(added+' accident row'+(added===1?'':'s')+' loaded. Existing matches were skipped.')}catch(e){showMessage(e.message)}}
async function insertUnique(table,rows,current,key){const existing=new Set(current.map(key)),fresh=rows.filter(x=>!existing.has(key(x)));if(!fresh.length)return 0;const {error}=await db.from(table).insert(fresh);if(error)throw error;return fresh.length}
function updateOperationsHomeCounts(){const c=$('#homeContactCount'),p=$('#homeComplaintCount'),a=$('#homeAccidentCount');if(c)c.textContent=currentUser?keyContacts.length+' contacts':'Sign in to view';if(p)p.textContent=currentUser?(complaintRecords.filter(x=>x.status!=='resolved').length+' open'):'Sign in to view';if(a)a.textContent=currentUser?(accidentRecords.filter(x=>x.status!=='closed').length+' open'):'Sign in to view'}

$('#contactSearch').oninput=renderKeyContacts;$('#contactCategory').onchange=renderKeyContacts;$('#addContact').onclick=()=>openContactEditor();$('#importContacts').onclick=importContacts;$('#contactForm').onsubmit=saveContact;
$('#complaintSearch').oninput=renderComplaints;$('#complaintFilter').onchange=renderComplaints;$('#addComplaint').onclick=()=>openComplaintEditor();$('#importComplaints').onclick=importComplaints;$('#complaintForm').onsubmit=saveComplaint;
$('#accidentSearch').oninput=renderAccidents;$('#accidentFilter').onchange=renderAccidents;$('#addAccident').onclick=()=>openAccidentEditor();$('#importAccidents').onclick=importAccidents;$('#accidentForm').onsubmit=saveAccident;
renderKeyContacts();renderComplaints();renderAccidents();loadOperations();
