(()=>{
  const boot=()=>{
    const grid=document.querySelector('.home-grid'),nav=document.querySelector('header nav');
    if(!grid||!nav)return;
    const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
    const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
    const now=new Date(),today=localDate(now);

    if(!document.getElementById('staffingHomeStyle')){
      const style=document.createElement('style');style.id='staffingHomeStyle';style.textContent=`
      .today-woods{max-width:860px;margin:0 auto 15px;background:#fff;border:1px solid var(--line);border-radius:16px;padding:15px 16px;box-shadow:0 5px 18px rgba(50,72,53,.08)}
      .today-head{display:flex;justify-content:space-between;gap:12px;align-items:center;border-bottom:1px solid var(--line);padding-bottom:10px}.today-head h3{margin:0;font-size:1.02rem}.today-date{color:var(--muted);font-size:.78rem;font-weight:700}.today-lines{display:grid;gap:9px;margin-top:10px}.today-line{display:grid;grid-template-columns:25px 1fr;gap:8px;align-items:start;font-size:.84rem;line-height:1.45}.today-line strong{color:var(--green-dark)}.today-line.notice{background:var(--green-pale);border-radius:10px;padding:9px}.today-line.priority{background:#fff3e8}.today-line.closed{background:#fff1ef;color:var(--red);border-radius:10px;padding:9px}.today-admin{display:none;margin-top:11px;padding-top:10px;border-top:1px solid var(--line);gap:7px}body.admin .today-admin{display:flex}.today-admin button{min-height:36px;padding:6px 10px}.notice-list{display:grid;gap:8px;margin:12px 0}.notice-row{border:1px solid var(--line);border-radius:11px;padding:10px}.notice-row-head{display:flex;justify-content:space-between;gap:10px}.notice-row p{margin:4px 0;color:var(--muted);font-size:.8rem}.notice-actions{display:flex;gap:6px;margin-top:7px}.notice-actions button{min-height:34px;padding:5px 8px}.notice-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.notice-form-grid .wide{grid-column:1/-1}.notice-form-grid input,.notice-form-grid textarea,.notice-form-grid select{width:100%;border:1px solid var(--line);border-radius:9px;padding:9px;font:inherit}.notice-form-grid textarea{min-height:85px}.notice-dialog-body{padding:17px}.notice-dialog-body h2{margin-top:0}.notice-dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}
      @media(max-width:680px){.today-woods{margin:0 3px 14px;padding:13px}.today-head{align-items:flex-start}.today-line{font-size:.8rem}.notice-form-grid{grid-template-columns:1fr}.notice-form-grid .wide{grid-column:auto}}
      `;document.head.appendChild(style);
    }

    if(!document.getElementById('staffingTab')){const b=document.getElementById('bookingsTab'),t=document.createElement('button');t.className='tab';t.id='staffingTab';t.type='button';t.textContent='Staffing';t.onclick=()=>location.href='staffing.html';b?.after(t)}
    if(!document.getElementById('staffingHomeTile')){const b=[...grid.querySelectorAll('.home-tile')].find(x=>x.textContent.includes('Table bookings')),t=document.createElement('button');t.className='home-tile';t.id='staffingHomeTile';t.type='button';t.innerHTML='<div><div class="tile-icon">👥</div><h3>Staffing</h3><p>See who is working, who opens and plan future days.</p></div><span class="tile-status">Open staffing calendar</span>';t.onclick=()=>location.href='staffing.html';b?.after(t)}

    let panel=document.getElementById('todayWoods');
    if(!panel){panel=document.createElement('section');panel.id='todayWoods';panel.className='today-woods';panel.innerHTML=`<div class="today-head"><h3>Today at Woods</h3><span class="today-date">${new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short'}).format(now)}</span></div><div class="today-lines" id="todayLines"><div class="today-line"><span>⏳</span><div>Loading today’s briefing…</div></div></div><div class="today-admin"><button class="btn" id="manageNotices">Manage notices</button><button class="btn" id="addNotice">+ Add notice</button></div>`;document.querySelector('#homeView .home-hero')?.after(panel)}

    if(!document.getElementById('noticeManager')){const d=document.createElement('dialog');d.id='noticeManager';d.innerHTML=`<div class="notice-dialog-body"><h2>Team notices</h2><p class="category">Admin only · choose when each notice appears on Today at Woods.</p><div id="noticeList" class="notice-list"></div><div class="notice-dialog-actions"><button class="btn" id="closeNoticeManager">Close</button><button class="btn primary" id="newNotice">+ Add notice</button></div></div>`;document.body.appendChild(d);const e=document.createElement('dialog');e.id='noticeEditor';e.innerHTML=`<form id="noticeForm" class="notice-dialog-body"><h2 id="noticeFormTitle">Add notice</h2><div class="notice-form-grid"><div class="field wide"><label>Notice</label><textarea id="noticeText" required maxlength="500" placeholder="e.g. New autumn menu starts Tuesday"></textarea></div><div class="field"><label>Starts</label><input id="noticeStart" type="date" required></div><div class="field"><label>Ends</label><input id="noticeEnd" type="date" required></div><div class="field"><label>Priority</label><select id="noticePriority"><option value="normal">Normal</option><option value="important">Important</option></select></div></div><div class="notice-dialog-actions"><button type="button" class="btn" id="cancelNotice">Cancel</button><button class="btn primary">Save notice</button></div></form>`;document.body.appendChild(e)}

    if(!window.supabase||!window.WOODS_CONFIG)return;const client=window.supabase.createClient(window.WOODS_CONFIG.supabaseUrl,window.WOODS_CONFIG.supabaseAnonKey);let user=null,isAdmin=false,editing=null;
    const lines=document.getElementById('todayLines');
    async function loadBrief(){const s=await client.auth.getSession();user=s.data.session?.user||null;if(!user){lines.innerHTML='<div class="today-line"><span>🔒</span><div>Sign in to see today’s briefing.</div></div>';return}const p=await client.from('profiles').select('role').eq('id',user.id).maybeSingle();isAdmin=p.data?.role==='admin';
      const [staffQ,bookQ,noticeQ]=await Promise.all([client.from('shop_staffing').select('is_closed,staff,opener,notes').eq('shift_date',today).maybeSingle(),client.from('table_bookings').select('booking_time,party_size,customer_name').eq('booking_date',today).order('booking_time'),client.from('team_notices').select('id,message,start_date,end_date,priority,active,created_at').eq('active',true).lte('start_date',today).gte('end_date',today).order('priority',{ascending:false}).order('created_at',{ascending:false})]);
      let html='';const r=staffQ.data;if(r?.is_closed)html+='<div class="today-line closed"><span>🔒</span><div><strong>Shop closed today</strong></div></div>';else if(r){const names=Object.entries(r.staff||{}).filter(([,v])=>!!v).map(([n])=>n);html+=`<div class="today-line"><span>👥</span><div><strong>Team:</strong> ${names.length?names.map(esc).join(', '):'No team marked in'}${r.opener?` · <strong>Opens:</strong> ${esc(r.opener)}`:''}</div></div>`}else html+='<div class="today-line"><span>👥</span><div>No staffing saved for today yet.</div></div>';
      const bookings=bookQ.data||[],covers=bookings.reduce((n,x)=>n+Number(x.party_size||0),0);html+=`<div class="today-line"><span>📅</span><div><strong>Bookings:</strong> ${bookings.length?`${bookings.length} today · ${covers} covers${bookings[0]?.booking_time?` · first at ${esc(String(bookings[0].booking_time).slice(0,5))}`:''}`:'None today'}</div></div>`;
      if(noticeQ.error&&noticeQ.error.code==='42P01'){if(isAdmin)html+='<div class="today-line notice"><span>📣</span><div><strong>Notices:</strong> one-time setup needed.</div></div>'}else (noticeQ.data||[]).forEach(n=>html+=`<div class="today-line notice ${n.priority==='important'?'priority':''}"><span>${n.priority==='important'?'⚠️':'📣'}</span><div>${esc(n.message)}</div></div>`);
      lines.innerHTML=html||'<div class="today-line"><span>✓</span><div>Nothing to flag today.</div></div>';
    }
    async function loadManager(){const q=await client.from('team_notices').select('*').order('end_date',{ascending:false}).limit(30),box=document.getElementById('noticeList');if(q.error){box.innerHTML='<div class="empty">Notices need the one-time database setup before they can be used.</div>';return}const data=q.data||[];box.innerHTML=data.length?data.map(n=>`<div class="notice-row"><div class="notice-row-head"><strong>${n.priority==='important'?'⚠️ Important':'📣 Notice'}</strong><span>${n.active?'Active':'Hidden'}</span></div><p>${esc(n.message)}</p><p>${esc(n.start_date)} → ${esc(n.end_date)}</p><div class="notice-actions"><button class="btn edit-notice" data-id="${n.id}">Edit</button><button class="btn toggle-notice" data-id="${n.id}" data-active="${n.active}">${n.active?'Hide':'Show'}</button></div></div>`).join(''):'<div class="empty">No notices yet.</div>';box.querySelectorAll('.edit-notice').forEach(b=>b.onclick=()=>openEditor(data.find(x=>String(x.id)===b.dataset.id)));box.querySelectorAll('.toggle-notice').forEach(b=>b.onclick=async()=>{await client.from('team_notices').update({active:b.dataset.active!=='true',updated_by:user.id,updated_at:new Date().toISOString()}).eq('id',b.dataset.id);loadManager();loadBrief()})}
    function openEditor(n=null){editing=n?.id||null;document.getElementById('noticeFormTitle').textContent=n?'Edit notice':'Add notice';document.getElementById('noticeText').value=n?.message||'';document.getElementById('noticeStart').value=n?.start_date||today;document.getElementById('noticeEnd').value=n?.end_date||today;document.getElementById('noticePriority').value=n?.priority||'normal';document.getElementById('noticeEditor').showModal()}
    document.getElementById('manageNotices').onclick=()=>{document.getElementById('noticeManager').showModal();loadManager()};document.getElementById('addNotice').onclick=()=>openEditor();document.getElementById('newNotice').onclick=()=>openEditor();document.getElementById('closeNoticeManager').onclick=()=>document.getElementById('noticeManager').close();document.getElementById('cancelNotice').onclick=()=>document.getElementById('noticeEditor').close();document.getElementById('noticeForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin)return;const row={message:document.getElementById('noticeText').value.trim(),start_date:document.getElementById('noticeStart').value,end_date:document.getElementById('noticeEnd').value,priority:document.getElementById('noticePriority').value,active:true,updated_by:user.id,updated_at:new Date().toISOString()};if(row.end_date<row.start_date){alert('End date must be on or after the start date.');return}const q=editing?await client.from('team_notices').update(row).eq('id',editing):await client.from('team_notices').insert({...row,created_by:user.id});if(q.error){alert('Could not save notice: '+q.error.message);return}document.getElementById('noticeEditor').close();editing=null;loadManager();loadBrief()};
    client.auth.onAuthStateChange(()=>setTimeout(loadBrief,100));loadBrief();
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
