-- Woods Team Hub: COGS module
-- Run this whole file once in the Supabase SQL Editor.
-- Uses the existing public.is_admin() helper already used by Team Hub.

create extension if not exists pgcrypto;

create table if not exists public.cogs_ingredients (
  id text primary key,
  name text not null check (length(trim(name)) > 0),
  unit text not null default 'each',
  pack_cost numeric(12,4),
  pack_qty numeric(12,4),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  check (pack_cost is null or pack_cost >= 0),
  check (pack_qty is null or pack_qty > 0)
);

create table if not exists public.cogs_menu_items (
  id text primary key,
  name text not null check (length(trim(name)) > 0),
  category text not null check (length(trim(category)) > 0),
  selling_price numeric(12,2) not null default 0 check (selling_price >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.cogs_recipes (
  id uuid primary key default gen_random_uuid(),
  menu_item_id text not null references public.cogs_menu_items(id) on delete cascade,
  ingredient_id text not null references public.cogs_ingredients(id) on delete restrict,
  quantity numeric(12,4) not null check (quantity > 0),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique(menu_item_id, ingredient_id)
);

create table if not exists public.cogs_addons (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (length(trim(name)) > 0),
  selling_price numeric(12,2) not null default 0 check (selling_price >= 0),
  ingredient_id text references public.cogs_ingredients(id) on delete set null,
  quantity numeric(12,4),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  check (quantity is null or quantity > 0)
);

create table if not exists public.cogs_audit (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_cogs_change()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  rid text;
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    new.created_by = coalesce(new.created_by, auth.uid());
    new.updated_by = coalesce(auth.uid(), new.updated_by);
    rid := new.id::text;
    insert into public.cogs_audit(table_name,record_id,action,changed_by,new_data)
    values(tg_table_name,rid,'created',auth.uid(),to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(),new.updated_by);
    rid := new.id::text;
    insert into public.cogs_audit(table_name,record_id,action,changed_by,previous_data,new_data)
    values(tg_table_name,rid,
      case when to_jsonb(old) ? 'active' and (old.active is true and new.active is false) then 'archived'
           when to_jsonb(old) ? 'active' and (old.active is false and new.active is true) then 'restored'
           else 'updated' end,
      auth.uid(),to_jsonb(old),to_jsonb(new));
    return new;
  else
    rid := old.id::text;
    insert into public.cogs_audit(table_name,record_id,action,changed_by,previous_data)
    values(tg_table_name,rid,'deleted',auth.uid(),to_jsonb(old));
    return old;
  end if;
end $$;

drop trigger if exists cogs_ingredients_audit on public.cogs_ingredients;
create trigger cogs_ingredients_audit before insert or update or delete on public.cogs_ingredients
for each row execute function public.audit_cogs_change();

drop trigger if exists cogs_menu_items_audit on public.cogs_menu_items;
create trigger cogs_menu_items_audit before insert or update or delete on public.cogs_menu_items
for each row execute function public.audit_cogs_change();

drop trigger if exists cogs_recipes_audit on public.cogs_recipes;
create trigger cogs_recipes_audit before insert or update or delete on public.cogs_recipes
for each row execute function public.audit_cogs_change();

drop trigger if exists cogs_addons_audit on public.cogs_addons;
create trigger cogs_addons_audit before insert or update or delete on public.cogs_addons
for each row execute function public.audit_cogs_change();

alter table public.cogs_ingredients enable row level security;
alter table public.cogs_menu_items enable row level security;
alter table public.cogs_recipes enable row level security;
alter table public.cogs_addons enable row level security;
alter table public.cogs_audit enable row level security;

drop policy if exists "Authenticated staff can read COGS ingredients" on public.cogs_ingredients;
create policy "Authenticated staff can read COGS ingredients" on public.cogs_ingredients
for select to authenticated using (active = true or public.is_admin());

drop policy if exists "Admins can manage COGS ingredients" on public.cogs_ingredients;
create policy "Admins can manage COGS ingredients" on public.cogs_ingredients
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Authenticated staff can read COGS menu" on public.cogs_menu_items;
create policy "Authenticated staff can read COGS menu" on public.cogs_menu_items
for select to authenticated using (active = true or public.is_admin());

drop policy if exists "Admins can manage COGS menu" on public.cogs_menu_items;
create policy "Admins can manage COGS menu" on public.cogs_menu_items
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Authenticated staff can read COGS recipes" on public.cogs_recipes;
create policy "Authenticated staff can read COGS recipes" on public.cogs_recipes
for select to authenticated using (true);

drop policy if exists "Admins can manage COGS recipes" on public.cogs_recipes;
create policy "Admins can manage COGS recipes" on public.cogs_recipes
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Authenticated staff can read COGS add-ons" on public.cogs_addons;
create policy "Authenticated staff can read COGS add-ons" on public.cogs_addons
for select to authenticated using (active = true or public.is_admin());

drop policy if exists "Admins can manage COGS add-ons" on public.cogs_addons;
create policy "Admins can manage COGS add-ons" on public.cogs_addons
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can read COGS audit" on public.cogs_audit;
create policy "Admins can read COGS audit" on public.cogs_audit
for select to authenticated using (public.is_admin());

create index if not exists cogs_ingredients_active_name_idx on public.cogs_ingredients(active,name);
create index if not exists cogs_menu_category_active_idx on public.cogs_menu_items(category,active,sort_order,name);
create index if not exists cogs_recipes_menu_idx on public.cogs_recipes(menu_item_id);
create index if not exists cogs_recipes_ingredient_idx on public.cogs_recipes(ingredient_id);
create index if not exists cogs_audit_record_idx on public.cogs_audit(table_name,record_id,changed_at desc);

grant select,insert,update,delete on public.cogs_ingredients to authenticated;
grant select,insert,update,delete on public.cogs_menu_items to authenticated;
grant select,insert,update,delete on public.cogs_recipes to authenticated;
grant select,insert,update,delete on public.cogs_addons to authenticated;
grant select on public.cogs_audit to authenticated;
grant usage,select on sequence public.cogs_audit_id_seq to authenticated;
