-- Woods Team Hub: editable COSHH register
-- Run this whole file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.coshh_products (
  id uuid primary key default gen_random_uuid(),
  product_name text not null check (length(trim(product_name)) > 0),
  supplier text not null default '',
  purpose text not null default '',
  hazard_classification text not null default '',
  symbols text not null default '',
  risk_assessment text not null default '',
  safe_usage_instructions text not null default '',
  first_aid_measures text not null default '',
  ppe_required text not null default '',
  storage_instructions text not null default '',
  spill_exposure_procedure text not null default '',
  sds_location text not null default '',
  review_date date,
  next_review_date date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.coshh_audit (
  id bigint generated by default as identity primary key,
  product_id uuid not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_coshh_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    insert into public.coshh_audit(product_id,action,changed_by,new_data)
    values(new.id,'created',auth.uid(),to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(),new.updated_by);
    insert into public.coshh_audit(product_id,action,changed_by,previous_data,new_data)
    values(new.id,case when old.active and not new.active then 'archived' else 'updated' end,auth.uid(),to_jsonb(old),to_jsonb(new));
    return new;
  else
    insert into public.coshh_audit(product_id,action,changed_by,previous_data)
    values(old.id,'deleted',auth.uid(),to_jsonb(old));
    return old;
  end if;
end $$;

drop trigger if exists coshh_products_audit_trigger on public.coshh_products;
create trigger coshh_products_audit_trigger
before insert or update or delete on public.coshh_products
for each row execute function public.audit_coshh_change();

alter table public.coshh_products enable row level security;
alter table public.coshh_audit enable row level security;

drop policy if exists "Staff can read active COSHH products" on public.coshh_products;
create policy "Staff can read active COSHH products"
on public.coshh_products for select to authenticated
using (active = true or public.is_admin());

drop policy if exists "Admins can manage COSHH products" on public.coshh_products;
create policy "Admins can manage COSHH products"
on public.coshh_products for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can read COSHH audit" on public.coshh_audit;
create policy "Admins can read COSHH audit"
on public.coshh_audit for select to authenticated
using (public.is_admin());

create index if not exists coshh_products_active_name_idx
  on public.coshh_products (product_name) where active = true;
create index if not exists coshh_products_review_idx
  on public.coshh_products (next_review_date) where active = true;
create index if not exists coshh_audit_product_idx
  on public.coshh_audit (product_id, changed_at desc);

grant select,insert,update,delete on public.coshh_products to authenticated;
grant select on public.coshh_audit to authenticated;

