create table if not exists public.handbook_sections (
  id bigint generated by default as identity primary key,
  title text not null,
  content jsonb not null default '[]'::jsonb,
  sort_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

alter table public.handbook_sections enable row level security;

drop policy if exists "Staff can read handbook" on public.handbook_sections;
create policy "Staff can read handbook"
on public.handbook_sections for select
to authenticated
using (active = true);

drop policy if exists "Admins can manage handbook" on public.handbook_sections;
create policy "Admins can manage handbook"
on public.handbook_sections for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create index if not exists handbook_sections_order_idx
on public.handbook_sections (sort_order)
where active = true;