-- Woods Team Hub: private Forms & Templates repository
-- Run this whole file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.document_templates (
  id uuid primary key default gen_random_uuid(),
  title text not null check (length(trim(title)) > 0),
  category text not null check (length(trim(category)) > 0),
  frequency text not null default '',
  description text not null default '',
  current_version integer not null default 1 check (current_version > 0),
  current_storage_path text not null,
  current_file_name text not null,
  current_mime_type text not null,
  current_file_size bigint not null default 0 check (current_file_size >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.document_template_versions (
  id bigint generated by default as identity primary key,
  template_id uuid not null references public.document_templates(id) on delete cascade,
  version integer not null check (version > 0),
  storage_path text not null,
  file_name text not null,
  mime_type text not null,
  file_size bigint not null default 0 check (file_size >= 0),
  uploaded_at timestamptz not null default now(),
  uploaded_by uuid references auth.users(id),
  unique (template_id, version),
  unique (storage_path)
);

create table if not exists public.document_audit (
  id bigint generated by default as identity primary key,
  template_id uuid not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_document_template_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    insert into public.document_audit(template_id,action,changed_by,new_data)
    values(new.id,'created',auth.uid(),to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(),new.updated_by);
    insert into public.document_audit(template_id,action,changed_by,previous_data,new_data)
    values(new.id,case when old.active and not new.active then 'archived' else 'updated' end,auth.uid(),to_jsonb(old),to_jsonb(new));
    return new;
  else
    insert into public.document_audit(template_id,action,changed_by,previous_data)
    values(old.id,'deleted',auth.uid(),to_jsonb(old));
    return old;
  end if;
end $$;

drop trigger if exists document_templates_audit_trigger on public.document_templates;
create trigger document_templates_audit_trigger
before insert or update or delete on public.document_templates
for each row execute function public.audit_document_template_change();

create index if not exists document_templates_active_category_idx
  on public.document_templates (category, title) where active = true;
create index if not exists document_template_versions_template_idx
  on public.document_template_versions (template_id, version desc);
create index if not exists document_audit_template_idx
  on public.document_audit (template_id, changed_at desc);

alter table public.document_templates enable row level security;
alter table public.document_template_versions enable row level security;
alter table public.document_audit enable row level security;

drop policy if exists "Staff can read active documents" on public.document_templates;
create policy "Staff can read active documents"
on public.document_templates for select to authenticated
using (active = true or public.is_admin());

drop policy if exists "Admins can manage documents" on public.document_templates;
create policy "Admins can manage documents"
on public.document_templates for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can read document versions" on public.document_template_versions;
create policy "Admins can read document versions"
on public.document_template_versions for select to authenticated
using (public.is_admin());

drop policy if exists "Admins can add document versions" on public.document_template_versions;
create policy "Admins can add document versions"
on public.document_template_versions for insert to authenticated
with check (public.is_admin() and uploaded_by = auth.uid());

drop policy if exists "Admins can remove document versions" on public.document_template_versions;
create policy "Admins can remove document versions"
on public.document_template_versions for delete to authenticated
using (public.is_admin());

drop policy if exists "Admins can read document audit" on public.document_audit;
create policy "Admins can read document audit"
on public.document_audit for select to authenticated
using (public.is_admin());

-- The bucket is private. Staff can access only the current file of an active
-- document; admins can upload and maintain every version.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'shop-documents',
  'shop-documents',
  false,
  10485760,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Staff can open current shop documents" on storage.objects;
create policy "Staff can open current shop documents"
on storage.objects for select to authenticated
using (
  bucket_id = 'shop-documents'
  and (
    public.is_admin()
    or exists (
      select 1 from public.document_templates d
      where d.active = true and d.current_storage_path = name
    )
  )
);

drop policy if exists "Admins can upload shop documents" on storage.objects;
create policy "Admins can upload shop documents"
on storage.objects for insert to authenticated
with check (bucket_id = 'shop-documents' and public.is_admin());

drop policy if exists "Admins can update shop documents" on storage.objects;
create policy "Admins can update shop documents"
on storage.objects for update to authenticated
using (bucket_id = 'shop-documents' and public.is_admin())
with check (bucket_id = 'shop-documents' and public.is_admin());

drop policy if exists "Admins can delete shop documents" on storage.objects;
create policy "Admins can delete shop documents"
on storage.objects for delete to authenticated
using (bucket_id = 'shop-documents' and public.is_admin());

