-- Woods Team Hub: staff profiles and consolidated activity-log support
-- Run this whole file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Give every newly-created Auth user a readable staff profile automatically.
create or replace function public.create_staff_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1), 'Staff member'),
    'staff'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_staff_profile_trigger on auth.users;
create trigger create_staff_profile_trigger
after insert on auth.users
for each row execute function public.create_staff_profile();

-- Backfill profiles for any Auth users already created.
insert into public.profiles (id, display_name, role)
select
  u.id,
  coalesce(nullif(trim(u.raw_user_meta_data ->> 'display_name'), ''), split_part(u.email, '@', 1), 'Staff member'),
  'staff'
from auth.users u
on conflict (id) do nothing;

create table if not exists public.booking_audit (
  id bigint generated by default as identity primary key,
  booking_id uuid not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_booking_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.booking_audit(booking_id, action, changed_by, new_data)
    values(new.id, 'created', auth.uid(), to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(), new.updated_by);
    insert into public.booking_audit(booking_id, action, changed_by, previous_data, new_data)
    values(new.id, 'updated', auth.uid(), to_jsonb(old), to_jsonb(new));
    return new;
  else
    insert into public.booking_audit(booking_id, action, changed_by, previous_data)
    values(old.id, 'deleted', auth.uid(), to_jsonb(old));
    return old;
  end if;
end;
$$;

drop trigger if exists table_bookings_audit_trigger on public.table_bookings;
create trigger table_bookings_audit_trigger
before insert or update or delete on public.table_bookings
for each row execute function public.audit_booking_change();

create table if not exists public.handbook_audit (
  id bigint generated by default as identity primary key,
  section_id bigint not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_handbook_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(), new.updated_by);
    insert into public.handbook_audit(section_id, action, changed_by, new_data)
    values(new.id, 'created', auth.uid(), to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(), new.updated_by);
    insert into public.handbook_audit(section_id, action, changed_by, previous_data, new_data)
    values(new.id, case when old.active and not new.active then 'archived' else 'updated' end, auth.uid(), to_jsonb(old), to_jsonb(new));
    return new;
  else
    insert into public.handbook_audit(section_id, action, changed_by, previous_data)
    values(old.id, 'deleted', auth.uid(), to_jsonb(old));
    return old;
  end if;
end;
$$;

drop trigger if exists handbook_sections_audit_trigger on public.handbook_sections;
create trigger handbook_sections_audit_trigger
before insert or update or delete on public.handbook_sections
for each row execute function public.audit_handbook_change();

alter table public.booking_audit enable row level security;
alter table public.handbook_audit enable row level security;

drop policy if exists "Admins can read booking audit" on public.booking_audit;
create policy "Admins can read booking audit"
on public.booking_audit for select to authenticated
using (public.is_admin());

drop policy if exists "Admins can read handbook audit" on public.handbook_audit;
create policy "Admins can read handbook audit"
on public.handbook_audit for select to authenticated
using (public.is_admin());

create index if not exists booking_audit_changed_idx on public.booking_audit (changed_at desc);
create index if not exists handbook_audit_changed_idx on public.handbook_audit (changed_at desc);

grant select on public.booking_audit to authenticated;
grant select on public.handbook_audit to authenticated;

