-- Woods Team Hub: supplier ordering and order history
-- Run this whole file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.order_suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  email text not null,
  email_subject text not null default 'Woods Coffee Shop',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid not null references public.order_suppliers(id) on delete cascade,
  item_name text not null,
  singular_phrase text not null,
  plural_phrase text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  unique (supplier_id, item_name)
);

create table if not exists public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid not null references public.order_suppliers(id),
  supplier_name text not null,
  supplier_email text not null,
  delivery_date date not null,
  email_subject text not null,
  email_body text not null,
  status text not null default 'prepared' check (status in ('prepared','sent','cancelled')),
  email_opened_at timestamptz,
  sent_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

alter table public.purchase_orders drop constraint if exists purchase_orders_status_check;
alter table public.purchase_orders add constraint purchase_orders_status_check check (status in ('prepared','sending','sent','cancelled'));
alter table public.purchase_orders add column if not exists provider_message_id text;
alter table public.purchase_orders add column if not exists last_send_error text;

create table if not exists public.purchase_order_lines (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.purchase_orders(id) on delete cascade,
  supplier_item_id uuid references public.order_items(id),
  item_name text not null,
  quantity integer not null check (quantity > 0),
  order_phrase text not null
);

create table if not exists public.order_audit (
  id bigint generated by default as identity primary key,
  order_id uuid not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_purchase_order_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    insert into public.order_audit(order_id, action, changed_by, new_data)
    values(new.id, 'created', auth.uid(), to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(), new.updated_by);
    insert into public.order_audit(order_id, action, changed_by, previous_data, new_data)
    values(new.id, case when new.status = 'sent' and old.status <> 'sent' then 'sent' when new.status = 'cancelled' and old.status <> 'cancelled' then 'cancelled' else 'updated' end, coalesce(auth.uid(), new.updated_by), to_jsonb(old), to_jsonb(new));
    return new;
  else
    insert into public.order_audit(order_id, action, changed_by, previous_data)
    values(old.id, 'deleted', auth.uid(), to_jsonb(old));
    return old;
  end if;
end $$;

drop trigger if exists purchase_orders_audit_trigger on public.purchase_orders;
create trigger purchase_orders_audit_trigger
before insert or update or delete on public.purchase_orders
for each row execute function public.audit_purchase_order_change();

alter table public.order_suppliers enable row level security;
alter table public.order_items enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_lines enable row level security;
alter table public.order_audit enable row level security;

drop policy if exists "Staff can read order suppliers" on public.order_suppliers;
create policy "Staff can read order suppliers" on public.order_suppliers for select to authenticated using (active or public.is_admin());
drop policy if exists "Admins can manage order suppliers" on public.order_suppliers;
create policy "Admins can manage order suppliers" on public.order_suppliers for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Staff can read order items" on public.order_items;
create policy "Staff can read order items" on public.order_items for select to authenticated using (active or public.is_admin());
drop policy if exists "Admins can manage order items" on public.order_items;
create policy "Admins can manage order items" on public.order_items for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Staff can read purchase orders" on public.purchase_orders;
create policy "Staff can read purchase orders" on public.purchase_orders for select to authenticated using (active or public.is_admin());
drop policy if exists "Staff can prepare purchase orders" on public.purchase_orders;
create policy "Staff can prepare purchase orders" on public.purchase_orders for insert to authenticated with check (created_by = auth.uid() and updated_by = auth.uid());
drop policy if exists "Creators and admins can update purchase orders" on public.purchase_orders;
create policy "Creators and admins can update purchase orders" on public.purchase_orders for update to authenticated
using (created_by = auth.uid() or public.is_admin()) with check (updated_by = auth.uid() and (created_by = auth.uid() or public.is_admin()));
drop policy if exists "Admins can delete purchase orders" on public.purchase_orders;
create policy "Admins can delete purchase orders" on public.purchase_orders for delete to authenticated using (public.is_admin());

drop policy if exists "Staff can read purchase order lines" on public.purchase_order_lines;
create policy "Staff can read purchase order lines" on public.purchase_order_lines for select to authenticated
using (exists (select 1 from public.purchase_orders o where o.id = order_id and (o.active or public.is_admin())));
drop policy if exists "Creators can add purchase order lines" on public.purchase_order_lines;
create policy "Creators can add purchase order lines" on public.purchase_order_lines for insert to authenticated
with check (exists (select 1 from public.purchase_orders o where o.id = order_id and o.created_by = auth.uid() and o.status = 'prepared'));

drop policy if exists "Admins can read order audit" on public.order_audit;
create policy "Admins can read order audit" on public.order_audit for select to authenticated using (public.is_admin());

create index if not exists purchase_orders_created_idx on public.purchase_orders (created_at desc) where active = true;
create index if not exists purchase_order_lines_order_idx on public.purchase_order_lines (order_id);
create index if not exists order_audit_changed_idx on public.order_audit (changed_at desc);

grant select,insert,update,delete on public.order_suppliers to authenticated;
grant select,insert,update,delete on public.order_items to authenticated;
grant select,insert,update,delete on public.purchase_orders to authenticated;
grant select,insert on public.purchase_order_lines to authenticated;
grant select on public.order_audit to authenticated;

insert into public.order_suppliers (name, email, email_subject)
values ('Aubrey Allen', 'sales@aubreyallen.co.uk', 'Woods Coffee Shop')
on conflict (name) do update set email = excluded.email, email_subject = excluded.email_subject, active = true, updated_at = now();

insert into public.order_items (supplier_id, item_name, singular_phrase, plural_phrase, sort_order)
select s.id, x.item_name, x.singular_phrase, x.plural_phrase, x.sort_order
from public.order_suppliers s
cross join (values
  ('Cotswold Sausages', 'pack of Cotswold Sausages', 'packs of Cotswold Sausages', 1),
  ('Streaky Bacon', 'pack of Streaky Bacon', 'packs of Streaky Bacon', 2),
  ('Black Pudding', 'Black Pudding', 'Black Puddings', 3),
  ('White Pudding', 'White Pudding', 'White Puddings', 4),
  ('Gala Pork Pie', 'Gala Pork Pie', 'Gala Pork Pies', 5)
) as x(item_name, singular_phrase, plural_phrase, sort_order)
where s.name = 'Aubrey Allen'
on conflict (supplier_id, item_name) do update set
  singular_phrase = excluded.singular_phrase,
  plural_phrase = excluded.plural_phrase,
  sort_order = excluded.sort_order,
  active = true;
