-- Woods Team Hub: staff training log
-- Run this whole file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.training_records (
  id uuid primary key default gen_random_uuid(),
  person_name text not null check (length(trim(person_name)) > 0),
  role text not null default '',
  training_name text not null check (length(trim(training_name)) > 0),
  training_date date,
  expiry_date date,
  completion_status text not null default 'completed' check (completion_status in ('required','completed')),
  assigned_date date,
  due_date date,
  additional_details text not null default '',
  signed_dated text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

-- Safe upgrade for projects that already have the original training table.
alter table public.training_records alter column training_date drop not null;
alter table public.training_records add column if not exists completion_status text not null default 'completed';
alter table public.training_records add column if not exists assigned_date date;
alter table public.training_records add column if not exists due_date date;
alter table public.training_records drop constraint if exists training_records_completion_status_check;
alter table public.training_records add constraint training_records_completion_status_check check (completion_status in ('required','completed'));
update public.training_records
set completion_status = coalesce(completion_status,'completed'),
    assigned_date = coalesce(assigned_date,training_date)
where completion_status is null or assigned_date is null;

create table if not exists public.training_audit (
  id bigint generated by default as identity primary key,
  training_record_id uuid not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_training_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    insert into public.training_audit(training_record_id,action,changed_by,new_data)
    values(new.id,'created',auth.uid(),to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(),new.updated_by);
    insert into public.training_audit(training_record_id,action,changed_by,previous_data,new_data)
    values(new.id,case when old.active and not new.active then 'archived' else 'updated' end,auth.uid(),to_jsonb(old),to_jsonb(new));
    return new;
  else
    insert into public.training_audit(training_record_id,action,changed_by,previous_data)
    values(old.id,'deleted',auth.uid(),to_jsonb(old));
    return old;
  end if;
end $$;

drop trigger if exists training_records_audit_trigger on public.training_records;
create trigger training_records_audit_trigger
before insert or update or delete on public.training_records
for each row execute function public.audit_training_change();

alter table public.training_records enable row level security;
alter table public.training_audit enable row level security;

drop policy if exists "Staff can read active training records" on public.training_records;
create policy "Staff can read active training records"
on public.training_records for select to authenticated
using (active = true or public.is_admin());

drop policy if exists "Admins can manage training records" on public.training_records;
create policy "Admins can manage training records"
on public.training_records for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can read training audit" on public.training_audit;
create policy "Admins can read training audit"
on public.training_audit for select to authenticated
using (public.is_admin());

create index if not exists training_records_active_person_idx
  on public.training_records (person_name, training_date desc) where active = true;
create index if not exists training_records_expiry_idx
  on public.training_records (expiry_date) where active = true and expiry_date is not null;
create index if not exists training_records_requirement_idx
  on public.training_records (due_date) where active = true and completion_status = 'required';
create index if not exists training_audit_record_idx
  on public.training_audit (training_record_id, changed_at desc);

grant select,insert,update,delete on public.training_records to authenticated;
grant select on public.training_audit to authenticated;
