-- Woods Team Hub: key contacts, complaints and accident records
-- Run this whole file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.key_contacts (
  id uuid primary key default gen_random_uuid(),
  organisation text not null check (length(trim(organisation)) > 0),
  category text not null default 'Supplier',
  contact_name text not null default '',
  phone text not null default '',
  email text not null default '',
  website text not null default '',
  notes text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.complaint_records (
  id uuid primary key default gen_random_uuid(),
  date_received date not null,
  time_received time,
  received_by text not null default '',
  method text not null default '',
  customer_name text not null check (length(trim(customer_name)) > 0),
  contact_details text not null default '',
  visit_date date,
  visit_time text not null default '',
  party_size text not null default '',
  table_number text not null default '',
  items_ordered text not null default '',
  item_linked text not null default '',
  batch_cooked text not null default '',
  supplier text not null default '',
  description text not null check (length(trim(description)) > 0),
  illness_details text not null default '',
  other_complaints text not null default '',
  complaint_count text not null default '',
  food_safety_review text not null default '',
  action_taken text not null default '',
  outcome text not null default '',
  status text not null default 'open' check (status in ('open','investigating','resolved')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.accident_records (
  id uuid primary key default gen_random_uuid(),
  incident_date date not null,
  incident_time text not null default '',
  location text not null default '',
  incident_type text not null default '',
  person_name text not null check (length(trim(person_name)) > 0),
  contact_details text not null default '',
  person_status text not null default '',
  age text not null default '',
  description text not null check (length(trim(description)) > 0),
  injury_nature text not null default '',
  body_part text not null default '',
  visible_injury text not null default '',
  person_account text not null default '',
  action_taken text not null default '',
  witness_names text not null default '',
  witness_contacts text not null default '',
  witness_status text not null default '',
  environmental_conditions text not null default '',
  follow_up text not null default '',
  completed_by text not null default '',
  completed_by_role text not null default '',
  status text not null default 'open' check (status in ('open','follow_up','closed')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.operations_audit (
  id bigint generated by default as identity primary key,
  record_type text not null,
  record_id uuid not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_operations_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    insert into public.operations_audit(record_type,record_id,action,changed_by,new_data)
    values(tg_table_name,new.id,'created',auth.uid(),to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(),new.updated_by);
    insert into public.operations_audit(record_type,record_id,action,changed_by,previous_data,new_data)
    values(tg_table_name,new.id,case when old.active and not new.active then 'archived' else 'updated' end,auth.uid(),to_jsonb(old),to_jsonb(new));
    return new;
  else
    insert into public.operations_audit(record_type,record_id,action,changed_by,previous_data)
    values(tg_table_name,old.id,'deleted',auth.uid(),to_jsonb(old));
    return old;
  end if;
end $$;

drop trigger if exists key_contacts_audit_trigger on public.key_contacts;
create trigger key_contacts_audit_trigger before insert or update or delete on public.key_contacts
for each row execute function public.audit_operations_change();
drop trigger if exists complaint_records_audit_trigger on public.complaint_records;
create trigger complaint_records_audit_trigger before insert or update or delete on public.complaint_records
for each row execute function public.audit_operations_change();
drop trigger if exists accident_records_audit_trigger on public.accident_records;
create trigger accident_records_audit_trigger before insert or update or delete on public.accident_records
for each row execute function public.audit_operations_change();

alter table public.key_contacts enable row level security;
alter table public.complaint_records enable row level security;
alter table public.accident_records enable row level security;
alter table public.operations_audit enable row level security;

drop policy if exists "Staff can read active key contacts" on public.key_contacts;
create policy "Staff can read active key contacts" on public.key_contacts for select to authenticated
using (active = true or public.is_admin());
drop policy if exists "Admins can manage key contacts" on public.key_contacts;
create policy "Admins can manage key contacts" on public.key_contacts for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Creators and admins can read complaints" on public.complaint_records;
create policy "Creators and admins can read complaints" on public.complaint_records for select to authenticated
using (public.is_admin() or created_by = auth.uid());
drop policy if exists "Staff can create complaints" on public.complaint_records;
create policy "Staff can create complaints" on public.complaint_records for insert to authenticated
with check (created_by = auth.uid() and updated_by = auth.uid());
drop policy if exists "Creators and admins can update complaints" on public.complaint_records;
create policy "Creators and admins can update complaints" on public.complaint_records for update to authenticated
using (public.is_admin() or created_by = auth.uid())
with check (updated_by = auth.uid() and (public.is_admin() or created_by = auth.uid()));
drop policy if exists "Admins can delete complaints" on public.complaint_records;
create policy "Admins can delete complaints" on public.complaint_records for delete to authenticated
using (public.is_admin());

drop policy if exists "Creators and admins can read accidents" on public.accident_records;
create policy "Creators and admins can read accidents" on public.accident_records for select to authenticated
using (public.is_admin() or created_by = auth.uid());
drop policy if exists "Staff can create accidents" on public.accident_records;
create policy "Staff can create accidents" on public.accident_records for insert to authenticated
with check (created_by = auth.uid() and updated_by = auth.uid());
drop policy if exists "Creators and admins can update accidents" on public.accident_records;
create policy "Creators and admins can update accidents" on public.accident_records for update to authenticated
using (public.is_admin() or created_by = auth.uid())
with check (updated_by = auth.uid() and (public.is_admin() or created_by = auth.uid()));
drop policy if exists "Admins can delete accidents" on public.accident_records;
create policy "Admins can delete accidents" on public.accident_records for delete to authenticated
using (public.is_admin());

drop policy if exists "Admins can read operations audit" on public.operations_audit;
create policy "Admins can read operations audit" on public.operations_audit for select to authenticated
using (public.is_admin());

create index if not exists key_contacts_active_name_idx on public.key_contacts (organisation) where active = true;
create index if not exists complaint_records_date_idx on public.complaint_records (date_received desc) where active = true;
create index if not exists accident_records_date_idx on public.accident_records (incident_date desc) where active = true;
create index if not exists operations_audit_record_idx on public.operations_audit (record_type,record_id,changed_at desc);

grant select,insert,update,delete on public.key_contacts to authenticated;
grant select,insert,update,delete on public.complaint_records to authenticated;
grant select,insert,update,delete on public.accident_records to authenticated;
grant select on public.operations_audit to authenticated;
