create table if not exists public.team_notices (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 500),
  start_date date not null,
  end_date date not null,
  priority text not null default 'normal' check (priority in ('normal','important')),
  active boolean not null default true,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_notices_dates check (end_date >= start_date)
);

alter table public.team_notices enable row level security;

drop policy if exists "notices authenticated read" on public.team_notices;
create policy "notices authenticated read"
on public.team_notices for select
to authenticated
using (true);

drop policy if exists "notices admin insert" on public.team_notices;
create policy "notices admin insert"
on public.team_notices for insert
to authenticated
with check (
  auth.uid() = created_by
  and auth.uid() = updated_by
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

drop policy if exists "notices admin update" on public.team_notices;
create policy "notices admin update"
on public.team_notices for update
to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
with check (
  auth.uid() = updated_by
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

drop policy if exists "notices admin delete" on public.team_notices;
create policy "notices admin delete"
on public.team_notices for delete
to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
