-- Woods Team Hub: secure, editable risk-assessment register
-- Run this whole file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.risk_assessments (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  assessment_type text not null check (assessment_type in ('fire','health_safety','food_safety')),
  scope text not null default '',
  responsible_person text not null,
  issue_date date not null,
  review_date date not null,
  approval_status text not null default 'draft' check (approval_status in ('draft','approved')),
  version integer not null default 1 check (version > 0),
  approved_at timestamptz,
  approved_by uuid references auth.users(id),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.risk_items (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references public.risk_assessments(id) on delete cascade,
  section_title text not null,
  hazard text not null,
  people_at_risk text not null default '',
  harm text not null default '',
  controls text not null,
  control_status text not null default 'yes' check (control_status in ('yes','no','na')),
  is_ccp boolean not null default false,
  critical_limit text not null default '',
  monitoring text not null default '',
  corrective_action text not null default '',
  likelihood smallint not null default 1 check (likelihood between 1 and 5),
  severity smallint not null default 1 check (severity between 1 and 5),
  action_required text not null default '',
  action_owner text not null default '',
  action_due date,
  action_status text not null default 'not_required' check (action_status in ('not_required','open','in_progress','complete')),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.risk_review_history (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null references public.risk_assessments(id) on delete cascade,
  version integer not null,
  review_note text not null default '',
  snapshot jsonb not null,
  reviewed_at timestamptz not null default now(),
  reviewed_by uuid not null references auth.users(id),
  unique (assessment_id, version)
);

create table if not exists public.risk_acknowledgements (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null references public.risk_assessments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  version integer not null,
  acknowledged_at timestamptz not null default now(),
  unique (assessment_id, user_id, version)
);

create table if not exists public.risk_audit (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id uuid not null,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  previous_data jsonb,
  new_data jsonb
);

create or replace function public.audit_risk_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.updated_at = now();
    insert into public.risk_audit(table_name,record_id,action,changed_by,new_data)
    values(tg_table_name,new.id,'created',auth.uid(),to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    new.updated_at = now();
    new.updated_by = coalesce(auth.uid(),new.updated_by);
    insert into public.risk_audit(table_name,record_id,action,changed_by,previous_data,new_data)
    values(tg_table_name,new.id,'updated',auth.uid(),to_jsonb(old),to_jsonb(new));
    return new;
  else
    insert into public.risk_audit(table_name,record_id,action,changed_by,previous_data)
    values(tg_table_name,old.id,'deleted',auth.uid(),to_jsonb(old));
    return old;
  end if;
end $$;

drop trigger if exists risk_assessments_audit_trigger on public.risk_assessments;
create trigger risk_assessments_audit_trigger before insert or update or delete on public.risk_assessments for each row execute function public.audit_risk_change();
drop trigger if exists risk_items_audit_trigger on public.risk_items;
create trigger risk_items_audit_trigger before insert or update or delete on public.risk_items for each row execute function public.audit_risk_change();

alter table public.risk_assessments enable row level security;
alter table public.risk_items enable row level security;
alter table public.risk_review_history enable row level security;
alter table public.risk_acknowledgements enable row level security;
alter table public.risk_audit enable row level security;

drop policy if exists "Staff can read risk assessments" on public.risk_assessments;
create policy "Staff can read risk assessments" on public.risk_assessments for select to authenticated using (active = true or public.is_admin());
drop policy if exists "Admins can manage risk assessments" on public.risk_assessments;
create policy "Admins can manage risk assessments" on public.risk_assessments for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Staff can read risk items" on public.risk_items;
create policy "Staff can read risk items" on public.risk_items for select to authenticated
using ((active and exists (select 1 from public.risk_assessments a where a.id = risk_items.assessment_id and a.active)) or public.is_admin());
drop policy if exists "Admins can manage risk items" on public.risk_items;
create policy "Admins can manage risk items" on public.risk_items for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Staff can read review history" on public.risk_review_history;
create policy "Staff can read review history" on public.risk_review_history for select to authenticated
using (exists (select 1 from public.risk_assessments a where a.id = risk_review_history.assessment_id and (a.active or public.is_admin())));
drop policy if exists "Admins can add review history" on public.risk_review_history;
create policy "Admins can add review history" on public.risk_review_history for insert to authenticated with check (public.is_admin() and reviewed_by = auth.uid());

drop policy if exists "Users can read own acknowledgements" on public.risk_acknowledgements;
create policy "Users can read own acknowledgements" on public.risk_acknowledgements for select to authenticated using (user_id = auth.uid() or public.is_admin());
drop policy if exists "Users can acknowledge assessments" on public.risk_acknowledgements;
create policy "Users can acknowledge assessments" on public.risk_acknowledgements for insert to authenticated
with check (user_id = auth.uid() and exists (select 1 from public.risk_assessments a where a.id = risk_acknowledgements.assessment_id and a.active and a.version = risk_acknowledgements.version));

drop policy if exists "Admins can read risk audit" on public.risk_audit;
create policy "Admins can read risk audit" on public.risk_audit for select to authenticated using (public.is_admin());

create index if not exists risk_items_assessment_order_idx on public.risk_items (assessment_id, sort_order) where active = true;
create index if not exists risk_items_actions_idx on public.risk_items (action_status, action_due) where active = true;
create index if not exists risk_assessments_review_idx on public.risk_assessments (review_date) where active = true;

create or replace function public.approve_risk_assessment(p_assessment_id uuid, p_review_note text default '')
returns integer language plpgsql security definer set search_path = public
as $$
declare
  current_assessment public.risk_assessments%rowtype;
  next_version integer;
  version_snapshot jsonb;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into current_assessment from public.risk_assessments where id = p_assessment_id and active for update;
  if not found then raise exception 'Assessment not found'; end if;
  next_version := current_assessment.version + 1;
  select jsonb_build_object(
    'assessment', to_jsonb(current_assessment),
    'items', coalesce(jsonb_agg(to_jsonb(i) order by i.sort_order) filter (where i.id is not null), '[]'::jsonb)
  ) into version_snapshot
  from public.risk_items i where i.assessment_id = p_assessment_id and i.active;
  insert into public.risk_review_history(assessment_id,version,review_note,snapshot,reviewed_by)
  values(p_assessment_id,next_version,coalesce(p_review_note,''),version_snapshot,auth.uid());
  update public.risk_assessments set version=next_version,approval_status='approved',approved_at=now(),approved_by=auth.uid(),updated_by=auth.uid()
  where id=p_assessment_id;
  return next_version;
end $$;
grant execute on function public.approve_risk_assessment(uuid,text) to authenticated;

insert into public.risk_assessments (slug,title,assessment_type,scope,responsible_person,issue_date,review_date,approval_status,version)
values
 ('fire','Fire Risk Assessment','fire','Fire precautions, evacuation and emergency arrangements for Woods Coffee Shop.','Lee Fesel','2025-10-31','2026-10-15','approved',1),
 ('health-safety','Health & Safety Risk Assessment','health_safety','Work activities, equipment and workplace hazards affecting staff, customers, contractors and visitors.','Lee Fesel','2025-10-31','2026-10-15','approved',1),
 ('food-safety','Food Safety Management','food_safety','HACCP-based controls from supplier collection and delivery through storage, preparation, cooking and service.','Lee Fesel','2025-10-30','2026-10-15','approved',1)
on conflict (slug) do nothing;

-- Woods-owned starter controls. Admins should check each control against actual premises and working practice.
insert into public.risk_items (assessment_id,section_title,hazard,people_at_risk,harm,controls,control_status,likelihood,severity,sort_order)
select a.id,v.section_title,v.hazard,v.people_at_risk,v.harm,v.controls,'yes',v.likelihood,v.severity,v.sort_order
from public.risk_assessments a
cross join (values
 ('Fire prevention','Combustible materials and ignition sources','Staff, customers, visitors and contractors','Burns, smoke inhalation or fatal injury','Keep waste, packaging and other combustibles away from heat and ignition sources. Remove waste routinely and keep storage controlled.',2,5,1),
 ('Electrical safety','Faulty or misused electrical equipment','Staff, customers, visitors and contractors','Electric shock, burns or fire','Visually check equipment, remove damaged items from use, avoid overloaded sockets and arrange competent inspection and repair.',2,5,2),
 ('Escape routes','Blocked or unsuitable emergency exits','Everyone on the premises','Delayed evacuation, smoke inhalation or burns','Keep escape routes and final exits clear, unlocked when occupied, signed and adequately lit. Check routes during opening checks.',1,5,3),
 ('Warning and detection','Fire not detected or alarm not heard','Everyone on the premises','Delayed evacuation and serious injury','Maintain suitable detection and warning arrangements. Test alarms at the planned frequency and record defects and action taken.',1,5,4),
 ('Firefighting equipment','Equipment missing, obstructed or unsuitable','Staff and anyone attempting first response','Fire spreads or unsafe attempt to fight it','Provide suitable accessible equipment, maintain it through a competent provider and train staff that evacuation takes priority.',1,5,5),
 ('Emergency plan and training','People do not know how to evacuate','Staff, customers and anyone needing assistance','Delay, panic, injury or fatality','Maintain an emergency plan, assembly point and arrangements for vulnerable people. Induct staff and practise evacuation drills.',2,5,6)
) as v(section_title,hazard,people_at_risk,harm,controls,likelihood,severity,sort_order)
where a.slug='fire' and not exists (select 1 from public.risk_items i where i.assessment_id=a.id);

insert into public.risk_items (assessment_id,section_title,hazard,people_at_risk,harm,controls,control_status,likelihood,severity,sort_order)
select a.id,v.section_title,v.hazard,v.people_at_risk,v.harm,v.controls,'yes',v.likelihood,v.severity,v.sort_order
from public.risk_assessments a
cross join (values
 ('Manual handling','Lifting, carrying, pushing or pulling loads','Staff and delivery personnel','Strains, sprains, crush injuries or musculoskeletal injury','Avoid unnecessary handling, split heavy loads, use suitable aids and team lifts, and train staff in safe handling.',2,3,1),
 ('Violence at work','Aggressive, threatening or violent behaviour','Staff and customers','Physical injury, distress or trauma','Use calm de-escalation, avoid lone confrontation, summon assistance or police when required and record incidents.',2,4,2),
 ('Slips and trips','Wet floors, trailing items or uneven access','Staff, customers, contractors and visitors','Falls, fractures, cuts or bruising','Clean spills promptly, use warning signs, keep routes clear, manage cables and check floors and entrances routinely.',3,3,3),
 ('Hot liquids and surfaces','Steam, hot drinks, hot water and heated equipment','Staff and customers','Scalds and burns','Use trained methods, stable containers, maintained equipment and clear communication when carrying or serving hot items.',3,3,4),
 ('Knives and sharp blades','Cutting equipment and broken items','Staff','Cuts, punctures or serious laceration','Use suitable equipment and technique, store blades safely, never leave knives in sinks and dispose of damaged sharps safely.',2,4,5),
 ('Electricity','Damaged equipment, leads, plugs or sockets','Staff, customers and contractors','Shock, burns, fire or fatal injury','Carry out user checks, keep electricity away from water, isolate faults and use competent persons for repair and inspection.',2,5,6),
 ('Cleaning chemicals','Exposure to hazardous cleaning substances','Staff and cleaners','Skin or eye injury, breathing difficulty or poisoning','Keep COSHH information, follow dilution and PPE instructions, retain labels and never mix chemicals.',2,4,7),
 ('Work equipment','Moving, hot or pressurised coffee and kitchen equipment','Staff','Crush, cut, burn or other equipment injury','Provide instructions and training, maintain guards and safety features, isolate before cleaning and remove faulty equipment from use.',2,4,8),
 ('Lone, young or expectant workers','Work circumstances increase individual vulnerability','Relevant staff members','Greater exposure to violence, manual handling or other workplace risks','Complete an individual assessment where needed, provide suitable supervision and adjust duties or hours to control identified risk.',2,4,9)
) as v(section_title,hazard,people_at_risk,harm,controls,likelihood,severity,sort_order)
where a.slug='health-safety' and not exists (select 1 from public.risk_items i where i.assessment_id=a.id);

insert into public.risk_items (assessment_id,section_title,hazard,people_at_risk,harm,controls,control_status,is_ccp,critical_limit,monitoring,corrective_action,likelihood,severity,sort_order)
select a.id,v.stage,v.hazard,'Customers and staff',v.harm,v.controls,'yes',v.is_ccp,v.critical_limit,v.monitoring,v.corrective_action,2,5,v.sort_order
from public.risk_assessments a
cross join (values
 ('Collection and delivery','Contaminated, damaged or incorrectly temperature-controlled food','Food poisoning, allergic reaction or physical injury','Use approved suppliers. Check condition, labelling, use-by dates, allergens and chilled or frozen condition on receipt.',false,'Follow product labelling and the Woods delivery acceptance limits.','Check every delivery and record exceptions.','Reject or isolate food that is damaged, contaminated, out of date or outside the accepted condition.',1),
 ('Storage','Growth of bacteria, cross-contamination or allergen cross-contact','Food poisoning or allergic reaction','Separate raw and ready-to-eat food, protect and label stock, rotate by date and maintain appropriate chilled, frozen and dry storage.',true,'Chilled food and freezer limits must match the documented Woods procedure and manufacturer instructions.','Check storage temperatures and stock condition at the defined frequency.','Move food to safe storage, assess exposure and discard when safety cannot be demonstrated.',2),
 ('Defrosting','Bacterial growth or contamination during thawing','Food poisoning','Defrost under refrigeration or by a validated safe method, contain drips and use within the defined period.',false,'Food must be fully defrosted before cooking unless manufacturer instructions allow otherwise.','Check method, time and condition before use.','Continue safe defrosting, cook immediately where appropriate, or discard if time or temperature safety is uncertain.',3),
 ('Preparation','Cross-contamination, allergen cross-contact or foreign objects','Food poisoning, allergic reaction or injury','Use effective hand hygiene, clean and disinfect food-contact surfaces, separate tasks and equipment, and follow the allergen procedure.',false,'Use Woods cleaning, separation and allergen controls for every preparation task.','Supervisor observation and pre-use checks.','Stop preparation, isolate affected food, reclean, replace utensils and remake where contamination may have occurred.',4),
 ('Cooking','Survival of harmful bacteria','Food poisoning','Use a validated cooking method and check the core temperature or equivalent time-and-temperature combination for higher-risk foods.',true,'Use the current Woods validated cooking limit and record exceptions.','Probe or otherwise validate representative higher-risk food using a clean calibrated thermometer.','Continue cooking and recheck, or discard if a safe result cannot be achieved or verified.',5),
 ('Hot holding','Growth of bacteria while food is held hot','Food poisoning','Keep hot-held food at the legal safe holding temperature, minimise holding time and protect it from contamination.',true,'63°C or above, unless using the permitted single period below this temperature.','Check and record hot-holding temperatures at the defined frequency.','Rapidly reheat once to a safe temperature or discard when the safe limit or permitted time is exceeded.',6),
 ('Cooling','Bacterial growth or toxin formation during slow cooling','Food poisoning','Cool food quickly in small portions or shallow containers, protect it, then refrigerate promptly.',true,'Follow the validated Woods cooling time and temperature limit.','Record cooling start, finish and temperature for relevant batches.','Use a faster safe cooling method or discard food when the validated limit is missed.',7),
 ('Displaying food','Contamination, allergen error or unsafe temperature','Food poisoning, allergic reaction or injury','Protect food, use clean utensils, separate allergen-sensitive items and control display time and temperature.',false,'Apply the documented chilled, hot-holding and time-control limits.','Check display protection, labels, time and temperature during service.','Remove affected food, correct labels or separation and discard when safety cannot be confirmed.',8),
 ('Reheating','Survival or growth of bacteria','Food poisoning','Reheat rapidly and thoroughly, normally only once, using a validated method.',true,'Use the current Woods validated reheating limit.','Check representative core temperature and record exceptions.','Continue reheating and recheck, or discard if a safe result cannot be achieved.',9),
 ('Service','Contamination, allergen misinformation or unsafe handling','Food poisoning or allergic reaction','Use clean service equipment, protect ready-to-eat food and follow the allergen matrix and escalation procedure before answering customers.',false,'Never guess allergen information; pause and verify when uncertain.','Observe service practice and investigate complaints or near misses.','Stop service of the affected item, correct information, remake safely and record the incident or near miss.',10)
) as v(stage,hazard,harm,controls,is_ccp,critical_limit,monitoring,corrective_action,sort_order)
where a.slug='food-safety' and not exists (select 1 from public.risk_items i where i.assessment_id=a.id);
